/*this file generated by GL_java_2_c.java ,dont modify it manual.*/
#include <stdio.h>
#include <string.h>
//#include "glad/glad.h"
#include "glfm.h"
#if TARGET_OS_IOS
#include <OpenGLES/ES2/gl.h>
#else
#include <GLES2/gl2.h>
#endif
//#include "GLFW/glfw3.h"
#include "linmath.h"

#include "jvm.h"
#include "jni_gui.h"

int org_mini_gl_GL_gladLoadGLES2Loader(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    

    int _re_val = 1;//gladLoadGLES2Loader();
    s32 ret_value = *((s32*)&_re_val);env->push_int(runtime->stack, ret_value);
    
    return 0;
}

int org_mini_gl_GL_glActiveTexture(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 ptexture = env->localvar_getInt(runtime, pos++);

    glActiveTexture((GLenum)ptexture);
    
    
    return 0;
}

int org_mini_gl_GL_glAttachShader(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pprogram = env->localvar_getInt(runtime, pos++);
    s32 pshader = env->localvar_getInt(runtime, pos++);

    glAttachShader((GLuint)pprogram, (GLuint)pshader);
    
    
    return 0;
}

int org_mini_gl_GL_glBindAttribLocation(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pprogram = env->localvar_getInt(runtime, pos++);
    s32 pindex = env->localvar_getInt(runtime, pos++);
    Instance *pname = env->localvar_getRefer(runtime, pos++);
    int offset_pname = env->localvar_getInt(runtime, pos++);
    __refer ptr_pname = NULL;
    if(pname){
        offset_pname *= env->data_type_bytes[pname->mb.arr_type_index];
        ptr_pname = pname->arr_body + offset_pname;
    }

    glBindAttribLocation((GLuint)pprogram, (GLuint)pindex, (const GLchar*)(ptr_pname));
    
    
    return 0;
}

int org_mini_gl_GL_glBindBuffer(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 ptarget = env->localvar_getInt(runtime, pos++);
    s32 pbuffer = env->localvar_getInt(runtime, pos++);

    glBindBuffer((GLenum)ptarget, (GLuint)pbuffer);
    
    
    return 0;
}

int org_mini_gl_GL_glBindFramebuffer(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 ptarget = env->localvar_getInt(runtime, pos++);
    s32 pframebuffer = env->localvar_getInt(runtime, pos++);

    glBindFramebuffer((GLenum)ptarget, (GLuint)pframebuffer);
    
    
    return 0;
}

int org_mini_gl_GL_glBindRenderbuffer(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 ptarget = env->localvar_getInt(runtime, pos++);
    s32 prenderbuffer = env->localvar_getInt(runtime, pos++);

    glBindRenderbuffer((GLenum)ptarget, (GLuint)prenderbuffer);
    
    
    return 0;
}

int org_mini_gl_GL_glBindTexture(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 ptarget = env->localvar_getInt(runtime, pos++);
    s32 ptexture = env->localvar_getInt(runtime, pos++);

    glBindTexture((GLenum)ptarget, (GLuint)ptexture);
    
    
    return 0;
}

int org_mini_gl_GL_glBlendColor(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    Int2Float pred;pred.i = env->localvar_getInt(runtime, pos++);
    Int2Float pgreen;pgreen.i = env->localvar_getInt(runtime, pos++);
    Int2Float pblue;pblue.i = env->localvar_getInt(runtime, pos++);
    Int2Float palpha;palpha.i = env->localvar_getInt(runtime, pos++);

    glBlendColor((GLfloat)pred.f, (GLfloat)pgreen.f, (GLfloat)pblue.f, (GLfloat)palpha.f);
    
    
    return 0;
}

int org_mini_gl_GL_glBlendEquation(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pmode = env->localvar_getInt(runtime, pos++);

    glBlendEquation((GLenum)pmode);
    
    
    return 0;
}

int org_mini_gl_GL_glBlendEquationSeparate(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pmodeRGB = env->localvar_getInt(runtime, pos++);
    s32 pmodeAlpha = env->localvar_getInt(runtime, pos++);

    glBlendEquationSeparate((GLenum)pmodeRGB, (GLenum)pmodeAlpha);
    
    
    return 0;
}

int org_mini_gl_GL_glBlendFunc(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 psfactor = env->localvar_getInt(runtime, pos++);
    s32 pdfactor = env->localvar_getInt(runtime, pos++);

    glBlendFunc((GLenum)psfactor, (GLenum)pdfactor);
    
    
    return 0;
}

int org_mini_gl_GL_glBlendFuncSeparate(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 psfactorRGB = env->localvar_getInt(runtime, pos++);
    s32 pdfactorRGB = env->localvar_getInt(runtime, pos++);
    s32 psfactorAlpha = env->localvar_getInt(runtime, pos++);
    s32 pdfactorAlpha = env->localvar_getInt(runtime, pos++);

    glBlendFuncSeparate((GLenum)psfactorRGB, (GLenum)pdfactorRGB, (GLenum)psfactorAlpha, (GLenum)pdfactorAlpha);
    
    
    return 0;
}

int org_mini_gl_GL_glBufferData(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 ptarget = env->localvar_getInt(runtime, pos++);
    intptr_t psize = env->localvar_getLong_2slot(runtime, pos);pos += 2;
    Instance *pdata = env->localvar_getRefer(runtime, pos++);
    int offset_pdata = env->localvar_getInt(runtime, pos++);
    __refer ptr_pdata = NULL;
    if(pdata){
        offset_pdata *= env->data_type_bytes[pdata->mb.arr_type_index];
        ptr_pdata = pdata->arr_body + offset_pdata;
    }
    s32 pusage = env->localvar_getInt(runtime, pos++);

    glBufferData((GLenum)ptarget, (GLsizeiptr)psize, (const void*)(ptr_pdata), (GLenum)pusage);
    
    
    return 0;
}

int org_mini_gl_GL_glBufferSubData(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 ptarget = env->localvar_getInt(runtime, pos++);
    intptr_t poffset = env->localvar_getLong_2slot(runtime, pos);pos += 2;
    intptr_t psize = env->localvar_getLong_2slot(runtime, pos);pos += 2;
    Instance *pdata = env->localvar_getRefer(runtime, pos++);
    int offset_pdata = env->localvar_getInt(runtime, pos++);
    __refer ptr_pdata = NULL;
    if(pdata){
        offset_pdata *= env->data_type_bytes[pdata->mb.arr_type_index];
        ptr_pdata = pdata->arr_body + offset_pdata;
    }

    glBufferSubData((GLenum)ptarget, (GLintptr)poffset, (GLsizeiptr)psize, (const void*)(ptr_pdata));
    
    
    return 0;
}

int org_mini_gl_GL_glCheckFramebufferStatus(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 ptarget = env->localvar_getInt(runtime, pos++);

    GLenum _re_val = glCheckFramebufferStatus((GLenum)ptarget);
    s32 ret_value = *((s32*)&_re_val);env->push_int(runtime->stack, ret_value);
    
    return 0;
}

int org_mini_gl_GL_glClear(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pmask = env->localvar_getInt(runtime, pos++);

    glClear((GLbitfield)pmask);
    
    
    return 0;
}

int org_mini_gl_GL_glClearColor(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    Int2Float pred;pred.i = env->localvar_getInt(runtime, pos++);
    Int2Float pgreen;pgreen.i = env->localvar_getInt(runtime, pos++);
    Int2Float pblue;pblue.i = env->localvar_getInt(runtime, pos++);
    Int2Float palpha;palpha.i = env->localvar_getInt(runtime, pos++);

    glClearColor((GLfloat)pred.f, (GLfloat)pgreen.f, (GLfloat)pblue.f, (GLfloat)palpha.f);
    
    
    return 0;
}

int org_mini_gl_GL_glClearDepthf(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    Int2Float pd;pd.i = env->localvar_getInt(runtime, pos++);

    glClearDepthf((GLfloat)pd.f);
    
    
    return 0;
}

int org_mini_gl_GL_glClearStencil(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 ps = env->localvar_getInt(runtime, pos++);

    glClearStencil((GLint)ps);
    
    
    return 0;
}

int org_mini_gl_GL_glColorMask(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pred = env->localvar_getInt(runtime, pos++);
    s32 pgreen = env->localvar_getInt(runtime, pos++);
    s32 pblue = env->localvar_getInt(runtime, pos++);
    s32 palpha = env->localvar_getInt(runtime, pos++);

    glColorMask((GLboolean)pred, (GLboolean)pgreen, (GLboolean)pblue, (GLboolean)palpha);
    
    
    return 0;
}

int org_mini_gl_GL_glCompileShader(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pshader = env->localvar_getInt(runtime, pos++);

    glCompileShader((GLuint)pshader);
    
    
    return 0;
}

int org_mini_gl_GL_glCompressedTexImage2D(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 ptarget = env->localvar_getInt(runtime, pos++);
    s32 plevel = env->localvar_getInt(runtime, pos++);
    s32 pinternalformat = env->localvar_getInt(runtime, pos++);
    s32 pwidth = env->localvar_getInt(runtime, pos++);
    s32 pheight = env->localvar_getInt(runtime, pos++);
    s32 pborder = env->localvar_getInt(runtime, pos++);
    s32 pimageSize = env->localvar_getInt(runtime, pos++);
    Instance *pdata = env->localvar_getRefer(runtime, pos++);
    int offset_pdata = env->localvar_getInt(runtime, pos++);
    __refer ptr_pdata = NULL;
    if(pdata){
        offset_pdata *= env->data_type_bytes[pdata->mb.arr_type_index];
        ptr_pdata = pdata->arr_body + offset_pdata;
    }

    glCompressedTexImage2D((GLenum)ptarget, (GLint)plevel, (GLenum)pinternalformat, (GLsizei)pwidth, (GLsizei)pheight, (GLint)pborder, (GLsizei)pimageSize, (const void*)(ptr_pdata));
    
    
    return 0;
}

int org_mini_gl_GL_glCompressedTexSubImage2D(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 ptarget = env->localvar_getInt(runtime, pos++);
    s32 plevel = env->localvar_getInt(runtime, pos++);
    s32 pxoffset = env->localvar_getInt(runtime, pos++);
    s32 pyoffset = env->localvar_getInt(runtime, pos++);
    s32 pwidth = env->localvar_getInt(runtime, pos++);
    s32 pheight = env->localvar_getInt(runtime, pos++);
    s32 pformat = env->localvar_getInt(runtime, pos++);
    s32 pimageSize = env->localvar_getInt(runtime, pos++);
    Instance *pdata = env->localvar_getRefer(runtime, pos++);
    int offset_pdata = env->localvar_getInt(runtime, pos++);
    __refer ptr_pdata = NULL;
    if(pdata){
        offset_pdata *= env->data_type_bytes[pdata->mb.arr_type_index];
        ptr_pdata = pdata->arr_body + offset_pdata;
    }

    glCompressedTexSubImage2D((GLenum)ptarget, (GLint)plevel, (GLint)pxoffset, (GLint)pyoffset, (GLsizei)pwidth, (GLsizei)pheight, (GLenum)pformat, (GLsizei)pimageSize, (const void*)(ptr_pdata));
    
    
    return 0;
}

int org_mini_gl_GL_glCopyTexImage2D(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 ptarget = env->localvar_getInt(runtime, pos++);
    s32 plevel = env->localvar_getInt(runtime, pos++);
    s32 pinternalformat = env->localvar_getInt(runtime, pos++);
    s32 px = env->localvar_getInt(runtime, pos++);
    s32 py = env->localvar_getInt(runtime, pos++);
    s32 pwidth = env->localvar_getInt(runtime, pos++);
    s32 pheight = env->localvar_getInt(runtime, pos++);
    s32 pborder = env->localvar_getInt(runtime, pos++);

    glCopyTexImage2D((GLenum)ptarget, (GLint)plevel, (GLenum)pinternalformat, (GLint)px, (GLint)py, (GLsizei)pwidth, (GLsizei)pheight, (GLint)pborder);
    
    
    return 0;
}

int org_mini_gl_GL_glCopyTexSubImage2D(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 ptarget = env->localvar_getInt(runtime, pos++);
    s32 plevel = env->localvar_getInt(runtime, pos++);
    s32 pxoffset = env->localvar_getInt(runtime, pos++);
    s32 pyoffset = env->localvar_getInt(runtime, pos++);
    s32 px = env->localvar_getInt(runtime, pos++);
    s32 py = env->localvar_getInt(runtime, pos++);
    s32 pwidth = env->localvar_getInt(runtime, pos++);
    s32 pheight = env->localvar_getInt(runtime, pos++);

    glCopyTexSubImage2D((GLenum)ptarget, (GLint)plevel, (GLint)pxoffset, (GLint)pyoffset, (GLint)px, (GLint)py, (GLsizei)pwidth, (GLsizei)pheight);
    
    
    return 0;
}

int org_mini_gl_GL_glCreateProgram(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    

    GLuint _re_val = glCreateProgram();
    s32 ret_value = *((s32*)&_re_val);env->push_int(runtime->stack, ret_value);
    
    return 0;
}

int org_mini_gl_GL_glCreateShader(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 ptype = env->localvar_getInt(runtime, pos++);

    GLuint _re_val = glCreateShader((GLenum)ptype);
    s32 ret_value = *((s32*)&_re_val);env->push_int(runtime->stack, ret_value);
    
    return 0;
}

int org_mini_gl_GL_glCullFace(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pmode = env->localvar_getInt(runtime, pos++);

    glCullFace((GLenum)pmode);
    
    
    return 0;
}

int org_mini_gl_GL_glDeleteBuffers(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pn = env->localvar_getInt(runtime, pos++);
    Instance *pbuffers = env->localvar_getRefer(runtime, pos++);
    int offset_pbuffers = env->localvar_getInt(runtime, pos++);
    __refer ptr_pbuffers = NULL;
    if(pbuffers){
        offset_pbuffers *= env->data_type_bytes[pbuffers->mb.arr_type_index];
        ptr_pbuffers = pbuffers->arr_body + offset_pbuffers;
    }

    glDeleteBuffers((GLsizei)pn, (const GLuint*)(ptr_pbuffers));
    
    
    return 0;
}

int org_mini_gl_GL_glDeleteFramebuffers(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pn = env->localvar_getInt(runtime, pos++);
    Instance *pframebuffers = env->localvar_getRefer(runtime, pos++);
    int offset_pframebuffers = env->localvar_getInt(runtime, pos++);
    __refer ptr_pframebuffers = NULL;
    if(pframebuffers){
        offset_pframebuffers *= env->data_type_bytes[pframebuffers->mb.arr_type_index];
        ptr_pframebuffers = pframebuffers->arr_body + offset_pframebuffers;
    }

    glDeleteFramebuffers((GLsizei)pn, (const GLuint*)(ptr_pframebuffers));
    
    
    return 0;
}

int org_mini_gl_GL_glDeleteProgram(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pprogram = env->localvar_getInt(runtime, pos++);

    glDeleteProgram((GLuint)pprogram);
    
    
    return 0;
}

int org_mini_gl_GL_glDeleteRenderbuffers(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pn = env->localvar_getInt(runtime, pos++);
    Instance *prenderbuffers = env->localvar_getRefer(runtime, pos++);
    int offset_prenderbuffers = env->localvar_getInt(runtime, pos++);
    __refer ptr_prenderbuffers = NULL;
    if(prenderbuffers){
        offset_prenderbuffers *= env->data_type_bytes[prenderbuffers->mb.arr_type_index];
        ptr_prenderbuffers = prenderbuffers->arr_body + offset_prenderbuffers;
    }

    glDeleteRenderbuffers((GLsizei)pn, (const GLuint*)(ptr_prenderbuffers));
    
    
    return 0;
}

int org_mini_gl_GL_glDeleteShader(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pshader = env->localvar_getInt(runtime, pos++);

    glDeleteShader((GLuint)pshader);
    
    
    return 0;
}

int org_mini_gl_GL_glDeleteTextures(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pn = env->localvar_getInt(runtime, pos++);
    Instance *ptextures = env->localvar_getRefer(runtime, pos++);
    int offset_ptextures = env->localvar_getInt(runtime, pos++);
    __refer ptr_ptextures = NULL;
    if(ptextures){
        offset_ptextures *= env->data_type_bytes[ptextures->mb.arr_type_index];
        ptr_ptextures = ptextures->arr_body + offset_ptextures;
    }

    glDeleteTextures((GLsizei)pn, (const GLuint*)(ptr_ptextures));
    
    
    return 0;
}

int org_mini_gl_GL_glDepthFunc(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pfunc = env->localvar_getInt(runtime, pos++);

    glDepthFunc((GLenum)pfunc);
    
    
    return 0;
}

int org_mini_gl_GL_glDepthMask(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pflag = env->localvar_getInt(runtime, pos++);

    glDepthMask((GLboolean)pflag);
    
    
    return 0;
}

int org_mini_gl_GL_glDepthRangef(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    Int2Float pn;pn.i = env->localvar_getInt(runtime, pos++);
    Int2Float pf;pf.i = env->localvar_getInt(runtime, pos++);

    glDepthRangef((GLfloat)pn.f, (GLfloat)pf.f);
    
    
    return 0;
}

int org_mini_gl_GL_glDetachShader(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pprogram = env->localvar_getInt(runtime, pos++);
    s32 pshader = env->localvar_getInt(runtime, pos++);

    glDetachShader((GLuint)pprogram, (GLuint)pshader);
    
    
    return 0;
}

int org_mini_gl_GL_glDisable(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pcap = env->localvar_getInt(runtime, pos++);

    glDisable((GLenum)pcap);
    
    
    return 0;
}

int org_mini_gl_GL_glDisableVertexAttribArray(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pindex = env->localvar_getInt(runtime, pos++);

    glDisableVertexAttribArray((GLuint)pindex);
    
    
    return 0;
}

int org_mini_gl_GL_glDrawArrays(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pmode = env->localvar_getInt(runtime, pos++);
    s32 pfirst = env->localvar_getInt(runtime, pos++);
    s32 pcount = env->localvar_getInt(runtime, pos++);

    glDrawArrays((GLenum)pmode, (GLint)pfirst, (GLsizei)pcount);
    
    
    return 0;
}

int org_mini_gl_GL_glDrawElements(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pmode = env->localvar_getInt(runtime, pos++);
    s32 pcount = env->localvar_getInt(runtime, pos++);
    s32 ptype = env->localvar_getInt(runtime, pos++);
    Instance *pindices = env->localvar_getRefer(runtime, pos++);
    int offset_pindices = env->localvar_getInt(runtime, pos++);
    __refer ptr_pindices = NULL;
    if(pindices){
        offset_pindices *= env->data_type_bytes[pindices->mb.arr_type_index];
        ptr_pindices = pindices->arr_body + offset_pindices;
    }

    glDrawElements((GLenum)pmode, (GLsizei)pcount, (GLenum)ptype, (const void*)(ptr_pindices));
    
    
    return 0;
}

int org_mini_gl_GL_glEnable(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pcap = env->localvar_getInt(runtime, pos++);

    glEnable((GLenum)pcap);
    
    
    return 0;
}

int org_mini_gl_GL_glEnableVertexAttribArray(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pindex = env->localvar_getInt(runtime, pos++);

    glEnableVertexAttribArray((GLuint)pindex);
    
    
    return 0;
}

int org_mini_gl_GL_glFinish(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    

    glFinish();
    
    
    return 0;
}

int org_mini_gl_GL_glFlush(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    

    glFlush();
    
    
    return 0;
}

int org_mini_gl_GL_glFramebufferRenderbuffer(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 ptarget = env->localvar_getInt(runtime, pos++);
    s32 pattachment = env->localvar_getInt(runtime, pos++);
    s32 prenderbuffertarget = env->localvar_getInt(runtime, pos++);
    s32 prenderbuffer = env->localvar_getInt(runtime, pos++);

    glFramebufferRenderbuffer((GLenum)ptarget, (GLenum)pattachment, (GLenum)prenderbuffertarget, (GLuint)prenderbuffer);
    
    
    return 0;
}

int org_mini_gl_GL_glFramebufferTexture2D(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 ptarget = env->localvar_getInt(runtime, pos++);
    s32 pattachment = env->localvar_getInt(runtime, pos++);
    s32 ptextarget = env->localvar_getInt(runtime, pos++);
    s32 ptexture = env->localvar_getInt(runtime, pos++);
    s32 plevel = env->localvar_getInt(runtime, pos++);

    glFramebufferTexture2D((GLenum)ptarget, (GLenum)pattachment, (GLenum)ptextarget, (GLuint)ptexture, (GLint)plevel);
    
    
    return 0;
}

int org_mini_gl_GL_glFrontFace(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pmode = env->localvar_getInt(runtime, pos++);

    glFrontFace((GLenum)pmode);
    
    
    return 0;
}

int org_mini_gl_GL_glGenBuffers(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pn = env->localvar_getInt(runtime, pos++);
    Instance *pbuffers = env->localvar_getRefer(runtime, pos++);
    int offset_pbuffers = env->localvar_getInt(runtime, pos++);
    __refer ptr_pbuffers = NULL;
    if(pbuffers){
        offset_pbuffers *= env->data_type_bytes[pbuffers->mb.arr_type_index];
        ptr_pbuffers = pbuffers->arr_body + offset_pbuffers;
    }

    glGenBuffers((GLsizei)pn, (GLuint*)(ptr_pbuffers));
    
    
    return 0;
}

int org_mini_gl_GL_glGenerateMipmap(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 ptarget = env->localvar_getInt(runtime, pos++);

    glGenerateMipmap((GLenum)ptarget);
    
    
    return 0;
}

int org_mini_gl_GL_glGenFramebuffers(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pn = env->localvar_getInt(runtime, pos++);
    Instance *pframebuffers = env->localvar_getRefer(runtime, pos++);
    int offset_pframebuffers = env->localvar_getInt(runtime, pos++);
    __refer ptr_pframebuffers = NULL;
    if(pframebuffers){
        offset_pframebuffers *= env->data_type_bytes[pframebuffers->mb.arr_type_index];
        ptr_pframebuffers = pframebuffers->arr_body + offset_pframebuffers;
    }

    glGenFramebuffers((GLsizei)pn, (GLuint*)(ptr_pframebuffers));
    
    
    return 0;
}

int org_mini_gl_GL_glGenRenderbuffers(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pn = env->localvar_getInt(runtime, pos++);
    Instance *prenderbuffers = env->localvar_getRefer(runtime, pos++);
    int offset_prenderbuffers = env->localvar_getInt(runtime, pos++);
    __refer ptr_prenderbuffers = NULL;
    if(prenderbuffers){
        offset_prenderbuffers *= env->data_type_bytes[prenderbuffers->mb.arr_type_index];
        ptr_prenderbuffers = prenderbuffers->arr_body + offset_prenderbuffers;
    }

    glGenRenderbuffers((GLsizei)pn, (GLuint*)(ptr_prenderbuffers));
    
    
    return 0;
}

int org_mini_gl_GL_glGenTextures(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pn = env->localvar_getInt(runtime, pos++);
    Instance *ptextures = env->localvar_getRefer(runtime, pos++);
    int offset_ptextures = env->localvar_getInt(runtime, pos++);
    __refer ptr_ptextures = NULL;
    if(ptextures){
        offset_ptextures *= env->data_type_bytes[ptextures->mb.arr_type_index];
        ptr_ptextures = ptextures->arr_body + offset_ptextures;
    }

    glGenTextures((GLsizei)pn, (GLuint*)(ptr_ptextures));
    
    
    return 0;
}

int org_mini_gl_GL_glGetActiveAttrib(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pprogram = env->localvar_getInt(runtime, pos++);
    s32 pindex = env->localvar_getInt(runtime, pos++);
    s32 pbufSize = env->localvar_getInt(runtime, pos++);
    Instance *plength = env->localvar_getRefer(runtime, pos++);
    int offset_plength = env->localvar_getInt(runtime, pos++);
    __refer ptr_plength = NULL;
    if(plength){
        offset_plength *= env->data_type_bytes[plength->mb.arr_type_index];
        ptr_plength = plength->arr_body + offset_plength;
    }
    Instance *psize = env->localvar_getRefer(runtime, pos++);
    int offset_psize = env->localvar_getInt(runtime, pos++);
    __refer ptr_psize = NULL;
    if(psize){
        offset_psize *= env->data_type_bytes[psize->mb.arr_type_index];
        ptr_psize = psize->arr_body + offset_psize;
    }
    Instance *ptype = env->localvar_getRefer(runtime, pos++);
    int offset_ptype = env->localvar_getInt(runtime, pos++);
    __refer ptr_ptype = NULL;
    if(ptype){
        offset_ptype *= env->data_type_bytes[ptype->mb.arr_type_index];
        ptr_ptype = ptype->arr_body + offset_ptype;
    }
    Instance *pname = env->localvar_getRefer(runtime, pos++);
    int offset_pname = env->localvar_getInt(runtime, pos++);
    __refer ptr_pname = NULL;
    if(pname){
        offset_pname *= env->data_type_bytes[pname->mb.arr_type_index];
        ptr_pname = pname->arr_body + offset_pname;
    }

    glGetActiveAttrib((GLuint)pprogram, (GLuint)pindex, (GLsizei)pbufSize, (GLsizei*)(ptr_plength), (GLint*)(ptr_psize), (GLenum*)(ptr_ptype), (GLchar*)(ptr_pname));
    
    
    return 0;
}

int org_mini_gl_GL_glGetActiveUniform(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pprogram = env->localvar_getInt(runtime, pos++);
    s32 pindex = env->localvar_getInt(runtime, pos++);
    s32 pbufSize = env->localvar_getInt(runtime, pos++);
    Instance *plength = env->localvar_getRefer(runtime, pos++);
    int offset_plength = env->localvar_getInt(runtime, pos++);
    __refer ptr_plength = NULL;
    if(plength){
        offset_plength *= env->data_type_bytes[plength->mb.arr_type_index];
        ptr_plength = plength->arr_body + offset_plength;
    }
    Instance *psize = env->localvar_getRefer(runtime, pos++);
    int offset_psize = env->localvar_getInt(runtime, pos++);
    __refer ptr_psize = NULL;
    if(psize){
        offset_psize *= env->data_type_bytes[psize->mb.arr_type_index];
        ptr_psize = psize->arr_body + offset_psize;
    }
    Instance *ptype = env->localvar_getRefer(runtime, pos++);
    int offset_ptype = env->localvar_getInt(runtime, pos++);
    __refer ptr_ptype = NULL;
    if(ptype){
        offset_ptype *= env->data_type_bytes[ptype->mb.arr_type_index];
        ptr_ptype = ptype->arr_body + offset_ptype;
    }
    Instance *pname = env->localvar_getRefer(runtime, pos++);
    int offset_pname = env->localvar_getInt(runtime, pos++);
    __refer ptr_pname = NULL;
    if(pname){
        offset_pname *= env->data_type_bytes[pname->mb.arr_type_index];
        ptr_pname = pname->arr_body + offset_pname;
    }

    glGetActiveUniform((GLuint)pprogram, (GLuint)pindex, (GLsizei)pbufSize, (GLsizei*)(ptr_plength), (GLint*)(ptr_psize), (GLenum*)(ptr_ptype), (GLchar*)(ptr_pname));
    
    
    return 0;
}

int org_mini_gl_GL_glGetAttachedShaders(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pprogram = env->localvar_getInt(runtime, pos++);
    s32 pmaxCount = env->localvar_getInt(runtime, pos++);
    Instance *pcount = env->localvar_getRefer(runtime, pos++);
    int offset_pcount = env->localvar_getInt(runtime, pos++);
    __refer ptr_pcount = NULL;
    if(pcount){
        offset_pcount *= env->data_type_bytes[pcount->mb.arr_type_index];
        ptr_pcount = pcount->arr_body + offset_pcount;
    }
    Instance *pshaders = env->localvar_getRefer(runtime, pos++);
    int offset_pshaders = env->localvar_getInt(runtime, pos++);
    __refer ptr_pshaders = NULL;
    if(pshaders){
        offset_pshaders *= env->data_type_bytes[pshaders->mb.arr_type_index];
        ptr_pshaders = pshaders->arr_body + offset_pshaders;
    }

    glGetAttachedShaders((GLuint)pprogram, (GLsizei)pmaxCount, (GLsizei*)(ptr_pcount), (GLuint*)(ptr_pshaders));
    
    
    return 0;
}

int org_mini_gl_GL_glGetAttribLocation(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pprogram = env->localvar_getInt(runtime, pos++);
    Instance *pname = env->localvar_getRefer(runtime, pos++);
    int offset_pname = env->localvar_getInt(runtime, pos++);
    __refer ptr_pname = NULL;
    if(pname){
        offset_pname *= env->data_type_bytes[pname->mb.arr_type_index];
        ptr_pname = pname->arr_body + offset_pname;
    }

    GLint _re_val = glGetAttribLocation((GLuint)pprogram, (const GLchar*)(ptr_pname));
    s32 ret_value = *((s32*)&_re_val);env->push_int(runtime->stack, ret_value);
    
    return 0;
}

int org_mini_gl_GL_glGetBooleanv(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 ppname = env->localvar_getInt(runtime, pos++);
    Instance *pdata = env->localvar_getRefer(runtime, pos++);
    int offset_pdata = env->localvar_getInt(runtime, pos++);
    __refer ptr_pdata = NULL;
    if(pdata){
        offset_pdata *= env->data_type_bytes[pdata->mb.arr_type_index];
        ptr_pdata = pdata->arr_body + offset_pdata;
    }

    glGetBooleanv((GLenum)ppname, (GLboolean*)(ptr_pdata));
    
    
    return 0;
}

int org_mini_gl_GL_glGetBufferParameteriv(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 ptarget = env->localvar_getInt(runtime, pos++);
    s32 ppname = env->localvar_getInt(runtime, pos++);
    Instance *pparams = env->localvar_getRefer(runtime, pos++);
    int offset_pparams = env->localvar_getInt(runtime, pos++);
    __refer ptr_pparams = NULL;
    if(pparams){
        offset_pparams *= env->data_type_bytes[pparams->mb.arr_type_index];
        ptr_pparams = pparams->arr_body + offset_pparams;
    }

    glGetBufferParameteriv((GLenum)ptarget, (GLenum)ppname, (GLint*)(ptr_pparams));
    
    
    return 0;
}

int org_mini_gl_GL_glGetError(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    

    GLenum _re_val = glGetError();
    s32 ret_value = *((s32*)&_re_val);env->push_int(runtime->stack, ret_value);
    
    return 0;
}

int org_mini_gl_GL_glGetFloatv(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 ppname = env->localvar_getInt(runtime, pos++);
    Instance *pdata = env->localvar_getRefer(runtime, pos++);
    int offset_pdata = env->localvar_getInt(runtime, pos++);
    __refer ptr_pdata = NULL;
    if(pdata){
        offset_pdata *= env->data_type_bytes[pdata->mb.arr_type_index];
        ptr_pdata = pdata->arr_body + offset_pdata;
    }

    glGetFloatv((GLenum)ppname, (GLfloat*)(ptr_pdata));
    
    
    return 0;
}

int org_mini_gl_GL_glGetFramebufferAttachmentParameteriv(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 ptarget = env->localvar_getInt(runtime, pos++);
    s32 pattachment = env->localvar_getInt(runtime, pos++);
    s32 ppname = env->localvar_getInt(runtime, pos++);
    Instance *pparams = env->localvar_getRefer(runtime, pos++);
    int offset_pparams = env->localvar_getInt(runtime, pos++);
    __refer ptr_pparams = NULL;
    if(pparams){
        offset_pparams *= env->data_type_bytes[pparams->mb.arr_type_index];
        ptr_pparams = pparams->arr_body + offset_pparams;
    }

    glGetFramebufferAttachmentParameteriv((GLenum)ptarget, (GLenum)pattachment, (GLenum)ppname, (GLint*)(ptr_pparams));
    
    
    return 0;
}

int org_mini_gl_GL_glGetIntegerv(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 ppname = env->localvar_getInt(runtime, pos++);
    Instance *pdata = env->localvar_getRefer(runtime, pos++);
    int offset_pdata = env->localvar_getInt(runtime, pos++);
    __refer ptr_pdata = NULL;
    if(pdata){
        offset_pdata *= env->data_type_bytes[pdata->mb.arr_type_index];
        ptr_pdata = pdata->arr_body + offset_pdata;
    }

    glGetIntegerv((GLenum)ppname, (GLint*)(ptr_pdata));
    
    
    return 0;
}

int org_mini_gl_GL_glGetProgramiv(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pprogram = env->localvar_getInt(runtime, pos++);
    s32 ppname = env->localvar_getInt(runtime, pos++);
    Instance *pparams = env->localvar_getRefer(runtime, pos++);
    int offset_pparams = env->localvar_getInt(runtime, pos++);
    __refer ptr_pparams = NULL;
    if(pparams){
        offset_pparams *= env->data_type_bytes[pparams->mb.arr_type_index];
        ptr_pparams = pparams->arr_body + offset_pparams;
    }

    glGetProgramiv((GLuint)pprogram, (GLenum)ppname, (GLint*)(ptr_pparams));
    
    
    return 0;
}

int org_mini_gl_GL_glGetProgramInfoLog(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pprogram = env->localvar_getInt(runtime, pos++);
    s32 pbufSize = env->localvar_getInt(runtime, pos++);
    Instance *plength = env->localvar_getRefer(runtime, pos++);
    int offset_plength = env->localvar_getInt(runtime, pos++);
    __refer ptr_plength = NULL;
    if(plength){
        offset_plength *= env->data_type_bytes[plength->mb.arr_type_index];
        ptr_plength = plength->arr_body + offset_plength;
    }
    Instance *pinfoLog = env->localvar_getRefer(runtime, pos++);
    int offset_pinfoLog = env->localvar_getInt(runtime, pos++);
    __refer ptr_pinfoLog = NULL;
    if(pinfoLog){
        offset_pinfoLog *= env->data_type_bytes[pinfoLog->mb.arr_type_index];
        ptr_pinfoLog = pinfoLog->arr_body + offset_pinfoLog;
    }

    glGetProgramInfoLog((GLuint)pprogram, (GLsizei)pbufSize, (GLsizei*)(ptr_plength), (GLchar*)(ptr_pinfoLog));
    
    
    return 0;
}

int org_mini_gl_GL_glGetRenderbufferParameteriv(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 ptarget = env->localvar_getInt(runtime, pos++);
    s32 ppname = env->localvar_getInt(runtime, pos++);
    Instance *pparams = env->localvar_getRefer(runtime, pos++);
    int offset_pparams = env->localvar_getInt(runtime, pos++);
    __refer ptr_pparams = NULL;
    if(pparams){
        offset_pparams *= env->data_type_bytes[pparams->mb.arr_type_index];
        ptr_pparams = pparams->arr_body + offset_pparams;
    }

    glGetRenderbufferParameteriv((GLenum)ptarget, (GLenum)ppname, (GLint*)(ptr_pparams));
    
    
    return 0;
}

int org_mini_gl_GL_glGetShaderiv(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pshader = env->localvar_getInt(runtime, pos++);
    s32 ppname = env->localvar_getInt(runtime, pos++);
    Instance *pparams = env->localvar_getRefer(runtime, pos++);
    int offset_pparams = env->localvar_getInt(runtime, pos++);
    __refer ptr_pparams = NULL;
    if(pparams){
        offset_pparams *= env->data_type_bytes[pparams->mb.arr_type_index];
        ptr_pparams = pparams->arr_body + offset_pparams;
    }

    glGetShaderiv((GLuint)pshader, (GLenum)ppname, (GLint*)(ptr_pparams));
    
    
    return 0;
}

int org_mini_gl_GL_glGetShaderInfoLog(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pshader = env->localvar_getInt(runtime, pos++);
    s32 pbufSize = env->localvar_getInt(runtime, pos++);
    Instance *plength = env->localvar_getRefer(runtime, pos++);
    int offset_plength = env->localvar_getInt(runtime, pos++);
    __refer ptr_plength = NULL;
    if(plength){
        offset_plength *= env->data_type_bytes[plength->mb.arr_type_index];
        ptr_plength = plength->arr_body + offset_plength;
    }
    Instance *pinfoLog = env->localvar_getRefer(runtime, pos++);
    int offset_pinfoLog = env->localvar_getInt(runtime, pos++);
    __refer ptr_pinfoLog = NULL;
    if(pinfoLog){
        offset_pinfoLog *= env->data_type_bytes[pinfoLog->mb.arr_type_index];
        ptr_pinfoLog = pinfoLog->arr_body + offset_pinfoLog;
    }

    glGetShaderInfoLog((GLuint)pshader, (GLsizei)pbufSize, (GLsizei*)(ptr_plength), (GLchar*)(ptr_pinfoLog));
    
    
    return 0;
}

int org_mini_gl_GL_glGetShaderPrecisionFormat(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pshadertype = env->localvar_getInt(runtime, pos++);
    s32 pprecisiontype = env->localvar_getInt(runtime, pos++);
    Instance *prange = env->localvar_getRefer(runtime, pos++);
    int offset_prange = env->localvar_getInt(runtime, pos++);
    __refer ptr_prange = NULL;
    if(prange){
        offset_prange *= env->data_type_bytes[prange->mb.arr_type_index];
        ptr_prange = prange->arr_body + offset_prange;
    }
    Instance *pprecision = env->localvar_getRefer(runtime, pos++);
    int offset_pprecision = env->localvar_getInt(runtime, pos++);
    __refer ptr_pprecision = NULL;
    if(pprecision){
        offset_pprecision *= env->data_type_bytes[pprecision->mb.arr_type_index];
        ptr_pprecision = pprecision->arr_body + offset_pprecision;
    }

    glGetShaderPrecisionFormat((GLenum)pshadertype, (GLenum)pprecisiontype, (GLint*)(ptr_prange), (GLint*)(ptr_pprecision));
    
    
    return 0;
}

int org_mini_gl_GL_glGetShaderSource(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pshader = env->localvar_getInt(runtime, pos++);
    s32 pbufSize = env->localvar_getInt(runtime, pos++);
    Instance *plength = env->localvar_getRefer(runtime, pos++);
    int offset_plength = env->localvar_getInt(runtime, pos++);
    __refer ptr_plength = NULL;
    if(plength){
        offset_plength *= env->data_type_bytes[plength->mb.arr_type_index];
        ptr_plength = plength->arr_body + offset_plength;
    }
    Instance *psource = env->localvar_getRefer(runtime, pos++);
    int offset_psource = env->localvar_getInt(runtime, pos++);
    __refer ptr_psource = NULL;
    if(psource){
        offset_psource *= env->data_type_bytes[psource->mb.arr_type_index];
        ptr_psource = psource->arr_body + offset_psource;
    }

    glGetShaderSource((GLuint)pshader, (GLsizei)pbufSize, (GLsizei*)(ptr_plength), (GLchar*)(ptr_psource));
    
    
    return 0;
}

int org_mini_gl_GL_glGetString(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pname = env->localvar_getInt(runtime, pos++);

    const GLubyte* _re_val = glGetString((GLenum)pname);
    c8* _ptr_re_val = (c8*)_re_val;
    if (_ptr_re_val) {
        s32 bytes = strlen(_ptr_re_val);
        s32 j_t_bytes = sizeof(c8);
        Instance *_arr = env->jarray_create(bytes / j_t_bytes, DATATYPE_BYTE, NULL);
        memcpy(_arr->arr_body, _ptr_re_val,bytes);
        env->push_ref(runtime->stack, _arr);
    } else {
        env->push_ref(runtime->stack, NULL);
    }
    
    return 0;
}

int org_mini_gl_GL_glGetTexParameterfv(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 ptarget = env->localvar_getInt(runtime, pos++);
    s32 ppname = env->localvar_getInt(runtime, pos++);
    Instance *pparams = env->localvar_getRefer(runtime, pos++);
    int offset_pparams = env->localvar_getInt(runtime, pos++);
    __refer ptr_pparams = NULL;
    if(pparams){
        offset_pparams *= env->data_type_bytes[pparams->mb.arr_type_index];
        ptr_pparams = pparams->arr_body + offset_pparams;
    }

    glGetTexParameterfv((GLenum)ptarget, (GLenum)ppname, (GLfloat*)(ptr_pparams));
    
    
    return 0;
}

int org_mini_gl_GL_glGetTexParameteriv(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 ptarget = env->localvar_getInt(runtime, pos++);
    s32 ppname = env->localvar_getInt(runtime, pos++);
    Instance *pparams = env->localvar_getRefer(runtime, pos++);
    int offset_pparams = env->localvar_getInt(runtime, pos++);
    __refer ptr_pparams = NULL;
    if(pparams){
        offset_pparams *= env->data_type_bytes[pparams->mb.arr_type_index];
        ptr_pparams = pparams->arr_body + offset_pparams;
    }

    glGetTexParameteriv((GLenum)ptarget, (GLenum)ppname, (GLint*)(ptr_pparams));
    
    
    return 0;
}

int org_mini_gl_GL_glGetUniformfv(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pprogram = env->localvar_getInt(runtime, pos++);
    s32 plocation = env->localvar_getInt(runtime, pos++);
    Instance *pparams = env->localvar_getRefer(runtime, pos++);
    int offset_pparams = env->localvar_getInt(runtime, pos++);
    __refer ptr_pparams = NULL;
    if(pparams){
        offset_pparams *= env->data_type_bytes[pparams->mb.arr_type_index];
        ptr_pparams = pparams->arr_body + offset_pparams;
    }

    glGetUniformfv((GLuint)pprogram, (GLint)plocation, (GLfloat*)(ptr_pparams));
    
    
    return 0;
}

int org_mini_gl_GL_glGetUniformiv(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pprogram = env->localvar_getInt(runtime, pos++);
    s32 plocation = env->localvar_getInt(runtime, pos++);
    Instance *pparams = env->localvar_getRefer(runtime, pos++);
    int offset_pparams = env->localvar_getInt(runtime, pos++);
    __refer ptr_pparams = NULL;
    if(pparams){
        offset_pparams *= env->data_type_bytes[pparams->mb.arr_type_index];
        ptr_pparams = pparams->arr_body + offset_pparams;
    }

    glGetUniformiv((GLuint)pprogram, (GLint)plocation, (GLint*)(ptr_pparams));
    
    
    return 0;
}

int org_mini_gl_GL_glGetUniformLocation(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pprogram = env->localvar_getInt(runtime, pos++);
    Instance *pname = env->localvar_getRefer(runtime, pos++);
    int offset_pname = env->localvar_getInt(runtime, pos++);
    __refer ptr_pname = NULL;
    if(pname){
        offset_pname *= env->data_type_bytes[pname->mb.arr_type_index];
        ptr_pname = pname->arr_body + offset_pname;
    }

    GLint _re_val = glGetUniformLocation((GLuint)pprogram, (const GLchar*)(ptr_pname));
    s32 ret_value = *((s32*)&_re_val);env->push_int(runtime->stack, ret_value);
    
    return 0;
}

int org_mini_gl_GL_glGetVertexAttribfv(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pindex = env->localvar_getInt(runtime, pos++);
    s32 ppname = env->localvar_getInt(runtime, pos++);
    Instance *pparams = env->localvar_getRefer(runtime, pos++);
    int offset_pparams = env->localvar_getInt(runtime, pos++);
    __refer ptr_pparams = NULL;
    if(pparams){
        offset_pparams *= env->data_type_bytes[pparams->mb.arr_type_index];
        ptr_pparams = pparams->arr_body + offset_pparams;
    }

    glGetVertexAttribfv((GLuint)pindex, (GLenum)ppname, (GLfloat*)(ptr_pparams));
    
    
    return 0;
}

int org_mini_gl_GL_glGetVertexAttribiv(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pindex = env->localvar_getInt(runtime, pos++);
    s32 ppname = env->localvar_getInt(runtime, pos++);
    Instance *pparams = env->localvar_getRefer(runtime, pos++);
    int offset_pparams = env->localvar_getInt(runtime, pos++);
    __refer ptr_pparams = NULL;
    if(pparams){
        offset_pparams *= env->data_type_bytes[pparams->mb.arr_type_index];
        ptr_pparams = pparams->arr_body + offset_pparams;
    }

    glGetVertexAttribiv((GLuint)pindex, (GLenum)ppname, (GLint*)(ptr_pparams));
    
    
    return 0;
}

int org_mini_gl_GL_glGetVertexAttribPointerv(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pindex = env->localvar_getInt(runtime, pos++);
    s32 ppname = env->localvar_getInt(runtime, pos++);
    Instance *ppointer = env->localvar_getRefer(runtime, pos++);
    ReferArr *ptr_ppointer = NULL;
    if(ppointer){
        ptr_ppointer = env->referarr_create(ppointer);
    }

    glGetVertexAttribPointerv((GLuint)pindex, (GLenum)ppname, (void**)(ptr_ppointer->arr_body));
    
    env->referarr_destory(ptr_ppointer);
    return 0;
}

int org_mini_gl_GL_glHint(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 ptarget = env->localvar_getInt(runtime, pos++);
    s32 pmode = env->localvar_getInt(runtime, pos++);

    glHint((GLenum)ptarget, (GLenum)pmode);
    
    
    return 0;
}

int org_mini_gl_GL_glIsBuffer(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pbuffer = env->localvar_getInt(runtime, pos++);

    GLboolean _re_val = glIsBuffer((GLuint)pbuffer);
    s32 ret_value = *((s32*)&_re_val);env->push_int(runtime->stack, ret_value);
    
    return 0;
}

int org_mini_gl_GL_glIsEnabled(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pcap = env->localvar_getInt(runtime, pos++);

    GLboolean _re_val = glIsEnabled((GLenum)pcap);
    s32 ret_value = *((s32*)&_re_val);env->push_int(runtime->stack, ret_value);
    
    return 0;
}

int org_mini_gl_GL_glIsFramebuffer(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pframebuffer = env->localvar_getInt(runtime, pos++);

    GLboolean _re_val = glIsFramebuffer((GLuint)pframebuffer);
    s32 ret_value = *((s32*)&_re_val);env->push_int(runtime->stack, ret_value);
    
    return 0;
}

int org_mini_gl_GL_glIsProgram(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pprogram = env->localvar_getInt(runtime, pos++);

    GLboolean _re_val = glIsProgram((GLuint)pprogram);
    s32 ret_value = *((s32*)&_re_val);env->push_int(runtime->stack, ret_value);
    
    return 0;
}

int org_mini_gl_GL_glIsRenderbuffer(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 prenderbuffer = env->localvar_getInt(runtime, pos++);

    GLboolean _re_val = glIsRenderbuffer((GLuint)prenderbuffer);
    s32 ret_value = *((s32*)&_re_val);env->push_int(runtime->stack, ret_value);
    
    return 0;
}

int org_mini_gl_GL_glIsShader(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pshader = env->localvar_getInt(runtime, pos++);

    GLboolean _re_val = glIsShader((GLuint)pshader);
    s32 ret_value = *((s32*)&_re_val);env->push_int(runtime->stack, ret_value);
    
    return 0;
}

int org_mini_gl_GL_glIsTexture(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 ptexture = env->localvar_getInt(runtime, pos++);

    GLboolean _re_val = glIsTexture((GLuint)ptexture);
    s32 ret_value = *((s32*)&_re_val);env->push_int(runtime->stack, ret_value);
    
    return 0;
}

int org_mini_gl_GL_glLineWidth(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    Int2Float pwidth;pwidth.i = env->localvar_getInt(runtime, pos++);

    glLineWidth((GLfloat)pwidth.f);
    
    
    return 0;
}

int org_mini_gl_GL_glLinkProgram(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pprogram = env->localvar_getInt(runtime, pos++);

    glLinkProgram((GLuint)pprogram);
    
    
    return 0;
}

int org_mini_gl_GL_glPixelStorei(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 ppname = env->localvar_getInt(runtime, pos++);
    s32 pparam = env->localvar_getInt(runtime, pos++);

    glPixelStorei((GLenum)ppname, (GLint)pparam);
    
    
    return 0;
}

int org_mini_gl_GL_glPolygonOffset(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    Int2Float pfactor;pfactor.i = env->localvar_getInt(runtime, pos++);
    Int2Float punits;punits.i = env->localvar_getInt(runtime, pos++);

    glPolygonOffset((GLfloat)pfactor.f, (GLfloat)punits.f);
    
    
    return 0;
}

int org_mini_gl_GL_glReadPixels(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 px = env->localvar_getInt(runtime, pos++);
    s32 py = env->localvar_getInt(runtime, pos++);
    s32 pwidth = env->localvar_getInt(runtime, pos++);
    s32 pheight = env->localvar_getInt(runtime, pos++);
    s32 pformat = env->localvar_getInt(runtime, pos++);
    s32 ptype = env->localvar_getInt(runtime, pos++);
    Instance *ppixels = env->localvar_getRefer(runtime, pos++);
    int offset_ppixels = env->localvar_getInt(runtime, pos++);
    __refer ptr_ppixels = NULL;
    if(ppixels){
        offset_ppixels *= env->data_type_bytes[ppixels->mb.arr_type_index];
        ptr_ppixels = ppixels->arr_body + offset_ppixels;
    }

    glReadPixels((GLint)px, (GLint)py, (GLsizei)pwidth, (GLsizei)pheight, (GLenum)pformat, (GLenum)ptype, (void*)(ptr_ppixels));
    
    
    return 0;
}

int org_mini_gl_GL_glReleaseShaderCompiler(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    

    glReleaseShaderCompiler();
    
    
    return 0;
}

int org_mini_gl_GL_glRenderbufferStorage(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 ptarget = env->localvar_getInt(runtime, pos++);
    s32 pinternalformat = env->localvar_getInt(runtime, pos++);
    s32 pwidth = env->localvar_getInt(runtime, pos++);
    s32 pheight = env->localvar_getInt(runtime, pos++);

    glRenderbufferStorage((GLenum)ptarget, (GLenum)pinternalformat, (GLsizei)pwidth, (GLsizei)pheight);
    
    
    return 0;
}

int org_mini_gl_GL_glSampleCoverage(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    Int2Float pvalue;pvalue.i = env->localvar_getInt(runtime, pos++);
    s32 pinvert = env->localvar_getInt(runtime, pos++);

    glSampleCoverage((GLfloat)pvalue.f, (GLboolean)pinvert);
    
    
    return 0;
}

int org_mini_gl_GL_glScissor(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 px = env->localvar_getInt(runtime, pos++);
    s32 py = env->localvar_getInt(runtime, pos++);
    s32 pwidth = env->localvar_getInt(runtime, pos++);
    s32 pheight = env->localvar_getInt(runtime, pos++);

    glScissor((GLint)px, (GLint)py, (GLsizei)pwidth, (GLsizei)pheight);
    
    
    return 0;
}

int org_mini_gl_GL_glShaderBinary(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pcount = env->localvar_getInt(runtime, pos++);
    Instance *pshaders = env->localvar_getRefer(runtime, pos++);
    int offset_pshaders = env->localvar_getInt(runtime, pos++);
    __refer ptr_pshaders = NULL;
    if(pshaders){
        offset_pshaders *= env->data_type_bytes[pshaders->mb.arr_type_index];
        ptr_pshaders = pshaders->arr_body + offset_pshaders;
    }
    s32 pbinaryformat = env->localvar_getInt(runtime, pos++);
    Instance *pbinary = env->localvar_getRefer(runtime, pos++);
    int offset_pbinary = env->localvar_getInt(runtime, pos++);
    __refer ptr_pbinary = NULL;
    if(pbinary){
        offset_pbinary *= env->data_type_bytes[pbinary->mb.arr_type_index];
        ptr_pbinary = pbinary->arr_body + offset_pbinary;
    }
    s32 plength = env->localvar_getInt(runtime, pos++);

    glShaderBinary((GLsizei)pcount, (const GLuint*)(ptr_pshaders), (GLenum)pbinaryformat, (const void*)(ptr_pbinary), (GLsizei)plength);
    
    
    return 0;
}

int org_mini_gl_GL_glShaderSource(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pshader = env->localvar_getInt(runtime, pos++);
    s32 pcount = env->localvar_getInt(runtime, pos++);
    Instance *pstring = env->localvar_getRefer(runtime, pos++);
    CStringArr *ptr_pstring = NULL;
    if(pstring){
        ptr_pstring = env->cstringarr_create(pstring);
    }
    Instance *plength = env->localvar_getRefer(runtime, pos++);
    int offset_plength = env->localvar_getInt(runtime, pos++);
    __refer ptr_plength = NULL;
    if(plength){
        offset_plength *= env->data_type_bytes[plength->mb.arr_type_index];
        ptr_plength = plength->arr_body + offset_plength;
    }

    glShaderSource((GLuint)pshader, (GLsizei)pcount, (const GLchar*const*)(ptr_pstring->arr_body), (const GLint*)(ptr_plength));
    
    env->cstringarr_destory(ptr_pstring);
    return 0;
}

int org_mini_gl_GL_glStencilFunc(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pfunc = env->localvar_getInt(runtime, pos++);
    s32 pref = env->localvar_getInt(runtime, pos++);
    s32 pmask = env->localvar_getInt(runtime, pos++);

    glStencilFunc((GLenum)pfunc, (GLint)pref, (GLuint)pmask);
    
    
    return 0;
}

int org_mini_gl_GL_glStencilFuncSeparate(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pface = env->localvar_getInt(runtime, pos++);
    s32 pfunc = env->localvar_getInt(runtime, pos++);
    s32 pref = env->localvar_getInt(runtime, pos++);
    s32 pmask = env->localvar_getInt(runtime, pos++);

    glStencilFuncSeparate((GLenum)pface, (GLenum)pfunc, (GLint)pref, (GLuint)pmask);
    
    
    return 0;
}

int org_mini_gl_GL_glStencilMask(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pmask = env->localvar_getInt(runtime, pos++);

    glStencilMask((GLuint)pmask);
    
    
    return 0;
}

int org_mini_gl_GL_glStencilMaskSeparate(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pface = env->localvar_getInt(runtime, pos++);
    s32 pmask = env->localvar_getInt(runtime, pos++);

    glStencilMaskSeparate((GLenum)pface, (GLuint)pmask);
    
    
    return 0;
}

int org_mini_gl_GL_glStencilOp(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pfail = env->localvar_getInt(runtime, pos++);
    s32 pzfail = env->localvar_getInt(runtime, pos++);
    s32 pzpass = env->localvar_getInt(runtime, pos++);

    glStencilOp((GLenum)pfail, (GLenum)pzfail, (GLenum)pzpass);
    
    
    return 0;
}

int org_mini_gl_GL_glStencilOpSeparate(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pface = env->localvar_getInt(runtime, pos++);
    s32 psfail = env->localvar_getInt(runtime, pos++);
    s32 pdpfail = env->localvar_getInt(runtime, pos++);
    s32 pdppass = env->localvar_getInt(runtime, pos++);

    glStencilOpSeparate((GLenum)pface, (GLenum)psfail, (GLenum)pdpfail, (GLenum)pdppass);
    
    
    return 0;
}

int org_mini_gl_GL_glTexImage2D(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 ptarget = env->localvar_getInt(runtime, pos++);
    s32 plevel = env->localvar_getInt(runtime, pos++);
    s32 pinternalformat = env->localvar_getInt(runtime, pos++);
    s32 pwidth = env->localvar_getInt(runtime, pos++);
    s32 pheight = env->localvar_getInt(runtime, pos++);
    s32 pborder = env->localvar_getInt(runtime, pos++);
    s32 pformat = env->localvar_getInt(runtime, pos++);
    s32 ptype = env->localvar_getInt(runtime, pos++);
    Instance *ppixels = env->localvar_getRefer(runtime, pos++);
    int offset_ppixels = env->localvar_getInt(runtime, pos++);
    __refer ptr_ppixels = NULL;
    if(ppixels){
        offset_ppixels *= env->data_type_bytes[ppixels->mb.arr_type_index];
        ptr_ppixels = ppixels->arr_body + offset_ppixels;
    }

    glTexImage2D((GLenum)ptarget, (GLint)plevel, (GLint)pinternalformat, (GLsizei)pwidth, (GLsizei)pheight, (GLint)pborder, (GLenum)pformat, (GLenum)ptype, (const void*)(ptr_ppixels));
    
    
    return 0;
}

int org_mini_gl_GL_glTexParameterf(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 ptarget = env->localvar_getInt(runtime, pos++);
    s32 ppname = env->localvar_getInt(runtime, pos++);
    Int2Float pparam;pparam.i = env->localvar_getInt(runtime, pos++);

    glTexParameterf((GLenum)ptarget, (GLenum)ppname, (GLfloat)pparam.f);
    
    
    return 0;
}

int org_mini_gl_GL_glTexParameterfv(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 ptarget = env->localvar_getInt(runtime, pos++);
    s32 ppname = env->localvar_getInt(runtime, pos++);
    Instance *pparams = env->localvar_getRefer(runtime, pos++);
    int offset_pparams = env->localvar_getInt(runtime, pos++);
    __refer ptr_pparams = NULL;
    if(pparams){
        offset_pparams *= env->data_type_bytes[pparams->mb.arr_type_index];
        ptr_pparams = pparams->arr_body + offset_pparams;
    }

    glTexParameterfv((GLenum)ptarget, (GLenum)ppname, (const GLfloat*)(ptr_pparams));
    
    
    return 0;
}

int org_mini_gl_GL_glTexParameteri(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 ptarget = env->localvar_getInt(runtime, pos++);
    s32 ppname = env->localvar_getInt(runtime, pos++);
    s32 pparam = env->localvar_getInt(runtime, pos++);

    glTexParameteri((GLenum)ptarget, (GLenum)ppname, (GLint)pparam);
    
    
    return 0;
}

int org_mini_gl_GL_glTexParameteriv(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 ptarget = env->localvar_getInt(runtime, pos++);
    s32 ppname = env->localvar_getInt(runtime, pos++);
    Instance *pparams = env->localvar_getRefer(runtime, pos++);
    int offset_pparams = env->localvar_getInt(runtime, pos++);
    __refer ptr_pparams = NULL;
    if(pparams){
        offset_pparams *= env->data_type_bytes[pparams->mb.arr_type_index];
        ptr_pparams = pparams->arr_body + offset_pparams;
    }

    glTexParameteriv((GLenum)ptarget, (GLenum)ppname, (const GLint*)(ptr_pparams));
    
    
    return 0;
}

int org_mini_gl_GL_glTexSubImage2D(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 ptarget = env->localvar_getInt(runtime, pos++);
    s32 plevel = env->localvar_getInt(runtime, pos++);
    s32 pxoffset = env->localvar_getInt(runtime, pos++);
    s32 pyoffset = env->localvar_getInt(runtime, pos++);
    s32 pwidth = env->localvar_getInt(runtime, pos++);
    s32 pheight = env->localvar_getInt(runtime, pos++);
    s32 pformat = env->localvar_getInt(runtime, pos++);
    s32 ptype = env->localvar_getInt(runtime, pos++);
    Instance *ppixels = env->localvar_getRefer(runtime, pos++);
    int offset_ppixels = env->localvar_getInt(runtime, pos++);
    __refer ptr_ppixels = NULL;
    if(ppixels){
        offset_ppixels *= env->data_type_bytes[ppixels->mb.arr_type_index];
        ptr_ppixels = ppixels->arr_body + offset_ppixels;
    }

    glTexSubImage2D((GLenum)ptarget, (GLint)plevel, (GLint)pxoffset, (GLint)pyoffset, (GLsizei)pwidth, (GLsizei)pheight, (GLenum)pformat, (GLenum)ptype, (const void*)(ptr_ppixels));
    
    
    return 0;
}

int org_mini_gl_GL_glUniform1f(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 plocation = env->localvar_getInt(runtime, pos++);
    Int2Float pv0;pv0.i = env->localvar_getInt(runtime, pos++);

    glUniform1f((GLint)plocation, (GLfloat)pv0.f);
    
    
    return 0;
}

int org_mini_gl_GL_glUniform1fv(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 plocation = env->localvar_getInt(runtime, pos++);
    s32 pcount = env->localvar_getInt(runtime, pos++);
    Instance *pvalue = env->localvar_getRefer(runtime, pos++);
    int offset_pvalue = env->localvar_getInt(runtime, pos++);
    __refer ptr_pvalue = NULL;
    if(pvalue){
        offset_pvalue *= env->data_type_bytes[pvalue->mb.arr_type_index];
        ptr_pvalue = pvalue->arr_body + offset_pvalue;
    }

    glUniform1fv((GLint)plocation, (GLsizei)pcount, (const GLfloat*)(ptr_pvalue));
    
    
    return 0;
}

int org_mini_gl_GL_glUniform1i(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 plocation = env->localvar_getInt(runtime, pos++);
    s32 pv0 = env->localvar_getInt(runtime, pos++);

    glUniform1i((GLint)plocation, (GLint)pv0);
    
    
    return 0;
}

int org_mini_gl_GL_glUniform1iv(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 plocation = env->localvar_getInt(runtime, pos++);
    s32 pcount = env->localvar_getInt(runtime, pos++);
    Instance *pvalue = env->localvar_getRefer(runtime, pos++);
    int offset_pvalue = env->localvar_getInt(runtime, pos++);
    __refer ptr_pvalue = NULL;
    if(pvalue){
        offset_pvalue *= env->data_type_bytes[pvalue->mb.arr_type_index];
        ptr_pvalue = pvalue->arr_body + offset_pvalue;
    }

    glUniform1iv((GLint)plocation, (GLsizei)pcount, (const GLint*)(ptr_pvalue));
    
    
    return 0;
}

int org_mini_gl_GL_glUniform2f(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 plocation = env->localvar_getInt(runtime, pos++);
    Int2Float pv0;pv0.i = env->localvar_getInt(runtime, pos++);
    Int2Float pv1;pv1.i = env->localvar_getInt(runtime, pos++);

    glUniform2f((GLint)plocation, (GLfloat)pv0.f, (GLfloat)pv1.f);
    
    
    return 0;
}

int org_mini_gl_GL_glUniform2fv(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 plocation = env->localvar_getInt(runtime, pos++);
    s32 pcount = env->localvar_getInt(runtime, pos++);
    Instance *pvalue = env->localvar_getRefer(runtime, pos++);
    int offset_pvalue = env->localvar_getInt(runtime, pos++);
    __refer ptr_pvalue = NULL;
    if(pvalue){
        offset_pvalue *= env->data_type_bytes[pvalue->mb.arr_type_index];
        ptr_pvalue = pvalue->arr_body + offset_pvalue;
    }

    glUniform2fv((GLint)plocation, (GLsizei)pcount, (const GLfloat*)(ptr_pvalue));
    
    
    return 0;
}

int org_mini_gl_GL_glUniform2i(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 plocation = env->localvar_getInt(runtime, pos++);
    s32 pv0 = env->localvar_getInt(runtime, pos++);
    s32 pv1 = env->localvar_getInt(runtime, pos++);

    glUniform2i((GLint)plocation, (GLint)pv0, (GLint)pv1);
    
    
    return 0;
}

int org_mini_gl_GL_glUniform2iv(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 plocation = env->localvar_getInt(runtime, pos++);
    s32 pcount = env->localvar_getInt(runtime, pos++);
    Instance *pvalue = env->localvar_getRefer(runtime, pos++);
    int offset_pvalue = env->localvar_getInt(runtime, pos++);
    __refer ptr_pvalue = NULL;
    if(pvalue){
        offset_pvalue *= env->data_type_bytes[pvalue->mb.arr_type_index];
        ptr_pvalue = pvalue->arr_body + offset_pvalue;
    }

    glUniform2iv((GLint)plocation, (GLsizei)pcount, (const GLint*)(ptr_pvalue));
    
    
    return 0;
}

int org_mini_gl_GL_glUniform3f(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 plocation = env->localvar_getInt(runtime, pos++);
    Int2Float pv0;pv0.i = env->localvar_getInt(runtime, pos++);
    Int2Float pv1;pv1.i = env->localvar_getInt(runtime, pos++);
    Int2Float pv2;pv2.i = env->localvar_getInt(runtime, pos++);

    glUniform3f((GLint)plocation, (GLfloat)pv0.f, (GLfloat)pv1.f, (GLfloat)pv2.f);
    
    
    return 0;
}

int org_mini_gl_GL_glUniform3fv(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 plocation = env->localvar_getInt(runtime, pos++);
    s32 pcount = env->localvar_getInt(runtime, pos++);
    Instance *pvalue = env->localvar_getRefer(runtime, pos++);
    int offset_pvalue = env->localvar_getInt(runtime, pos++);
    __refer ptr_pvalue = NULL;
    if(pvalue){
        offset_pvalue *= env->data_type_bytes[pvalue->mb.arr_type_index];
        ptr_pvalue = pvalue->arr_body + offset_pvalue;
    }

    glUniform3fv((GLint)plocation, (GLsizei)pcount, (const GLfloat*)(ptr_pvalue));
    
    
    return 0;
}

int org_mini_gl_GL_glUniform3i(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 plocation = env->localvar_getInt(runtime, pos++);
    s32 pv0 = env->localvar_getInt(runtime, pos++);
    s32 pv1 = env->localvar_getInt(runtime, pos++);
    s32 pv2 = env->localvar_getInt(runtime, pos++);

    glUniform3i((GLint)plocation, (GLint)pv0, (GLint)pv1, (GLint)pv2);
    
    
    return 0;
}

int org_mini_gl_GL_glUniform3iv(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 plocation = env->localvar_getInt(runtime, pos++);
    s32 pcount = env->localvar_getInt(runtime, pos++);
    Instance *pvalue = env->localvar_getRefer(runtime, pos++);
    int offset_pvalue = env->localvar_getInt(runtime, pos++);
    __refer ptr_pvalue = NULL;
    if(pvalue){
        offset_pvalue *= env->data_type_bytes[pvalue->mb.arr_type_index];
        ptr_pvalue = pvalue->arr_body + offset_pvalue;
    }

    glUniform3iv((GLint)plocation, (GLsizei)pcount, (const GLint*)(ptr_pvalue));
    
    
    return 0;
}

int org_mini_gl_GL_glUniform4f(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 plocation = env->localvar_getInt(runtime, pos++);
    Int2Float pv0;pv0.i = env->localvar_getInt(runtime, pos++);
    Int2Float pv1;pv1.i = env->localvar_getInt(runtime, pos++);
    Int2Float pv2;pv2.i = env->localvar_getInt(runtime, pos++);
    Int2Float pv3;pv3.i = env->localvar_getInt(runtime, pos++);

    glUniform4f((GLint)plocation, (GLfloat)pv0.f, (GLfloat)pv1.f, (GLfloat)pv2.f, (GLfloat)pv3.f);
    
    
    return 0;
}

int org_mini_gl_GL_glUniform4fv(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 plocation = env->localvar_getInt(runtime, pos++);
    s32 pcount = env->localvar_getInt(runtime, pos++);
    Instance *pvalue = env->localvar_getRefer(runtime, pos++);
    int offset_pvalue = env->localvar_getInt(runtime, pos++);
    __refer ptr_pvalue = NULL;
    if(pvalue){
        offset_pvalue *= env->data_type_bytes[pvalue->mb.arr_type_index];
        ptr_pvalue = pvalue->arr_body + offset_pvalue;
    }

    glUniform4fv((GLint)plocation, (GLsizei)pcount, (const GLfloat*)(ptr_pvalue));
    
    
    return 0;
}

int org_mini_gl_GL_glUniform4i(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 plocation = env->localvar_getInt(runtime, pos++);
    s32 pv0 = env->localvar_getInt(runtime, pos++);
    s32 pv1 = env->localvar_getInt(runtime, pos++);
    s32 pv2 = env->localvar_getInt(runtime, pos++);
    s32 pv3 = env->localvar_getInt(runtime, pos++);

    glUniform4i((GLint)plocation, (GLint)pv0, (GLint)pv1, (GLint)pv2, (GLint)pv3);
    
    
    return 0;
}

int org_mini_gl_GL_glUniform4iv(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 plocation = env->localvar_getInt(runtime, pos++);
    s32 pcount = env->localvar_getInt(runtime, pos++);
    Instance *pvalue = env->localvar_getRefer(runtime, pos++);
    int offset_pvalue = env->localvar_getInt(runtime, pos++);
    __refer ptr_pvalue = NULL;
    if(pvalue){
        offset_pvalue *= env->data_type_bytes[pvalue->mb.arr_type_index];
        ptr_pvalue = pvalue->arr_body + offset_pvalue;
    }

    glUniform4iv((GLint)plocation, (GLsizei)pcount, (const GLint*)(ptr_pvalue));
    
    
    return 0;
}

int org_mini_gl_GL_glUniformMatrix2fv(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 plocation = env->localvar_getInt(runtime, pos++);
    s32 pcount = env->localvar_getInt(runtime, pos++);
    s32 ptranspose = env->localvar_getInt(runtime, pos++);
    Instance *pvalue = env->localvar_getRefer(runtime, pos++);
    int offset_pvalue = env->localvar_getInt(runtime, pos++);
    __refer ptr_pvalue = NULL;
    if(pvalue){
        offset_pvalue *= env->data_type_bytes[pvalue->mb.arr_type_index];
        ptr_pvalue = pvalue->arr_body + offset_pvalue;
    }

    glUniformMatrix2fv((GLint)plocation, (GLsizei)pcount, (GLboolean)ptranspose, (const GLfloat*)(ptr_pvalue));
    
    
    return 0;
}

int org_mini_gl_GL_glUniformMatrix3fv(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 plocation = env->localvar_getInt(runtime, pos++);
    s32 pcount = env->localvar_getInt(runtime, pos++);
    s32 ptranspose = env->localvar_getInt(runtime, pos++);
    Instance *pvalue = env->localvar_getRefer(runtime, pos++);
    int offset_pvalue = env->localvar_getInt(runtime, pos++);
    __refer ptr_pvalue = NULL;
    if(pvalue){
        offset_pvalue *= env->data_type_bytes[pvalue->mb.arr_type_index];
        ptr_pvalue = pvalue->arr_body + offset_pvalue;
    }

    glUniformMatrix3fv((GLint)plocation, (GLsizei)pcount, (GLboolean)ptranspose, (const GLfloat*)(ptr_pvalue));
    
    
    return 0;
}

int org_mini_gl_GL_glUniformMatrix4fv(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 plocation = env->localvar_getInt(runtime, pos++);
    s32 pcount = env->localvar_getInt(runtime, pos++);
    s32 ptranspose = env->localvar_getInt(runtime, pos++);
    Instance *pvalue = env->localvar_getRefer(runtime, pos++);
    int offset_pvalue = env->localvar_getInt(runtime, pos++);
    __refer ptr_pvalue = NULL;
    if(pvalue){
        offset_pvalue *= env->data_type_bytes[pvalue->mb.arr_type_index];
        ptr_pvalue = pvalue->arr_body + offset_pvalue;
    }

    glUniformMatrix4fv((GLint)plocation, (GLsizei)pcount, (GLboolean)ptranspose, (const GLfloat*)(ptr_pvalue));
    
    
    return 0;
}

int org_mini_gl_GL_glUseProgram(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pprogram = env->localvar_getInt(runtime, pos++);

    glUseProgram((GLuint)pprogram);
    
    
    return 0;
}

int org_mini_gl_GL_glValidateProgram(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pprogram = env->localvar_getInt(runtime, pos++);

    glValidateProgram((GLuint)pprogram);
    
    
    return 0;
}

int org_mini_gl_GL_glVertexAttrib1f(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pindex = env->localvar_getInt(runtime, pos++);
    Int2Float px;px.i = env->localvar_getInt(runtime, pos++);

    glVertexAttrib1f((GLuint)pindex, (GLfloat)px.f);
    
    
    return 0;
}

int org_mini_gl_GL_glVertexAttrib1fv(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pindex = env->localvar_getInt(runtime, pos++);
    Instance *pv = env->localvar_getRefer(runtime, pos++);
    int offset_pv = env->localvar_getInt(runtime, pos++);
    __refer ptr_pv = NULL;
    if(pv){
        offset_pv *= env->data_type_bytes[pv->mb.arr_type_index];
        ptr_pv = pv->arr_body + offset_pv;
    }

    glVertexAttrib1fv((GLuint)pindex, (const GLfloat*)(ptr_pv));
    
    
    return 0;
}

int org_mini_gl_GL_glVertexAttrib2f(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pindex = env->localvar_getInt(runtime, pos++);
    Int2Float px;px.i = env->localvar_getInt(runtime, pos++);
    Int2Float py;py.i = env->localvar_getInt(runtime, pos++);

    glVertexAttrib2f((GLuint)pindex, (GLfloat)px.f, (GLfloat)py.f);
    
    
    return 0;
}

int org_mini_gl_GL_glVertexAttrib2fv(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pindex = env->localvar_getInt(runtime, pos++);
    Instance *pv = env->localvar_getRefer(runtime, pos++);
    int offset_pv = env->localvar_getInt(runtime, pos++);
    __refer ptr_pv = NULL;
    if(pv){
        offset_pv *= env->data_type_bytes[pv->mb.arr_type_index];
        ptr_pv = pv->arr_body + offset_pv;
    }

    glVertexAttrib2fv((GLuint)pindex, (const GLfloat*)(ptr_pv));
    
    
    return 0;
}

int org_mini_gl_GL_glVertexAttrib3f(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pindex = env->localvar_getInt(runtime, pos++);
    Int2Float px;px.i = env->localvar_getInt(runtime, pos++);
    Int2Float py;py.i = env->localvar_getInt(runtime, pos++);
    Int2Float pz;pz.i = env->localvar_getInt(runtime, pos++);

    glVertexAttrib3f((GLuint)pindex, (GLfloat)px.f, (GLfloat)py.f, (GLfloat)pz.f);
    
    
    return 0;
}

int org_mini_gl_GL_glVertexAttrib3fv(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pindex = env->localvar_getInt(runtime, pos++);
    Instance *pv = env->localvar_getRefer(runtime, pos++);
    int offset_pv = env->localvar_getInt(runtime, pos++);
    __refer ptr_pv = NULL;
    if(pv){
        offset_pv *= env->data_type_bytes[pv->mb.arr_type_index];
        ptr_pv = pv->arr_body + offset_pv;
    }

    glVertexAttrib3fv((GLuint)pindex, (const GLfloat*)(ptr_pv));
    
    
    return 0;
}

int org_mini_gl_GL_glVertexAttrib4f(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pindex = env->localvar_getInt(runtime, pos++);
    Int2Float px;px.i = env->localvar_getInt(runtime, pos++);
    Int2Float py;py.i = env->localvar_getInt(runtime, pos++);
    Int2Float pz;pz.i = env->localvar_getInt(runtime, pos++);
    Int2Float pw;pw.i = env->localvar_getInt(runtime, pos++);

    glVertexAttrib4f((GLuint)pindex, (GLfloat)px.f, (GLfloat)py.f, (GLfloat)pz.f, (GLfloat)pw.f);
    
    
    return 0;
}

int org_mini_gl_GL_glVertexAttrib4fv(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pindex = env->localvar_getInt(runtime, pos++);
    Instance *pv = env->localvar_getRefer(runtime, pos++);
    int offset_pv = env->localvar_getInt(runtime, pos++);
    __refer ptr_pv = NULL;
    if(pv){
        offset_pv *= env->data_type_bytes[pv->mb.arr_type_index];
        ptr_pv = pv->arr_body + offset_pv;
    }

    glVertexAttrib4fv((GLuint)pindex, (const GLfloat*)(ptr_pv));
    
    
    return 0;
}

int org_mini_gl_GL_glVertexAttribPointer(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 pindex = env->localvar_getInt(runtime, pos++);
    s32 psize = env->localvar_getInt(runtime, pos++);
    s32 ptype = env->localvar_getInt(runtime, pos++);
    s32 pnormalized = env->localvar_getInt(runtime, pos++);
    s32 pstride = env->localvar_getInt(runtime, pos++);
    Instance *ppointer = env->localvar_getRefer(runtime, pos++);
    int offset_ppointer = env->localvar_getInt(runtime, pos++);
    __refer ptr_ppointer = NULL;
    if(ppointer){
        offset_ppointer *= env->data_type_bytes[ppointer->mb.arr_type_index];
        ptr_ppointer = ppointer->arr_body + offset_ppointer;
    }

    glVertexAttribPointer((GLuint)pindex, (GLint)psize, (GLenum)ptype, (GLboolean)pnormalized, (GLsizei)pstride, (const void*)(ptr_ppointer));
    
    
    return 0;
}

int org_mini_gl_GL_glViewport(Runtime *runtime, JClass *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    s32 px = env->localvar_getInt(runtime, pos++);
    s32 py = env->localvar_getInt(runtime, pos++);
    s32 pwidth = env->localvar_getInt(runtime, pos++);
    s32 pheight = env->localvar_getInt(runtime, pos++);

    glViewport((GLint)px, (GLint)py, (GLsizei)pwidth, (GLsizei)pheight);
    
    
    return 0;
}




static java_native_method method_gl_table[] = {

{"org/mini/gl/GL",  "gladLoadGLES2Loader",  "()I",  org_mini_gl_GL_gladLoadGLES2Loader},
{"org/mini/gl/GL",  "glActiveTexture",  "(I)V",  org_mini_gl_GL_glActiveTexture},
{"org/mini/gl/GL",  "glAttachShader",  "(II)V",  org_mini_gl_GL_glAttachShader},
{"org/mini/gl/GL",  "glBindAttribLocation",  "(II[B)V",  org_mini_gl_GL_glBindAttribLocation},
{"org/mini/gl/GL",  "glBindBuffer",  "(II)V",  org_mini_gl_GL_glBindBuffer},
{"org/mini/gl/GL",  "glBindFramebuffer",  "(II)V",  org_mini_gl_GL_glBindFramebuffer},
{"org/mini/gl/GL",  "glBindRenderbuffer",  "(II)V",  org_mini_gl_GL_glBindRenderbuffer},
{"org/mini/gl/GL",  "glBindTexture",  "(II)V",  org_mini_gl_GL_glBindTexture},
{"org/mini/gl/GL",  "glBlendColor",  "(FFFF)V",  org_mini_gl_GL_glBlendColor},
{"org/mini/gl/GL",  "glBlendEquation",  "(I)V",  org_mini_gl_GL_glBlendEquation},
{"org/mini/gl/GL",  "glBlendEquationSeparate",  "(II)V",  org_mini_gl_GL_glBlendEquationSeparate},
{"org/mini/gl/GL",  "glBlendFunc",  "(II)V",  org_mini_gl_GL_glBlendFunc},
{"org/mini/gl/GL",  "glBlendFuncSeparate",  "(IIII)V",  org_mini_gl_GL_glBlendFuncSeparate},
{"org/mini/gl/GL",  "glBufferData",  "(IJLjava/lang/Object;II)V",  org_mini_gl_GL_glBufferData},
{"org/mini/gl/GL",  "glBufferSubData",  "(IJJLjava/lang/Object;I)V",  org_mini_gl_GL_glBufferSubData},
{"org/mini/gl/GL",  "glCheckFramebufferStatus",  "(I)I",  org_mini_gl_GL_glCheckFramebufferStatus},
{"org/mini/gl/GL",  "glClear",  "(I)V",  org_mini_gl_GL_glClear},
{"org/mini/gl/GL",  "glClearColor",  "(FFFF)V",  org_mini_gl_GL_glClearColor},
{"org/mini/gl/GL",  "glClearDepthf",  "(F)V",  org_mini_gl_GL_glClearDepthf},
{"org/mini/gl/GL",  "glClearStencil",  "(I)V",  org_mini_gl_GL_glClearStencil},
{"org/mini/gl/GL",  "glColorMask",  "(IIII)V",  org_mini_gl_GL_glColorMask},
{"org/mini/gl/GL",  "glCompileShader",  "(I)V",  org_mini_gl_GL_glCompileShader},
{"org/mini/gl/GL",  "glCompressedTexImage2D",  "(IIIIIIILjava/lang/Object;I)V",  org_mini_gl_GL_glCompressedTexImage2D},
{"org/mini/gl/GL",  "glCompressedTexSubImage2D",  "(IIIIIIIILjava/lang/Object;I)V",  org_mini_gl_GL_glCompressedTexSubImage2D},
{"org/mini/gl/GL",  "glCopyTexImage2D",  "(IIIIIIII)V",  org_mini_gl_GL_glCopyTexImage2D},
{"org/mini/gl/GL",  "glCopyTexSubImage2D",  "(IIIIIIII)V",  org_mini_gl_GL_glCopyTexSubImage2D},
{"org/mini/gl/GL",  "glCreateProgram",  "()I",  org_mini_gl_GL_glCreateProgram},
{"org/mini/gl/GL",  "glCreateShader",  "(I)I",  org_mini_gl_GL_glCreateShader},
{"org/mini/gl/GL",  "glCullFace",  "(I)V",  org_mini_gl_GL_glCullFace},
{"org/mini/gl/GL",  "glDeleteBuffers",  "(I[II)V",  org_mini_gl_GL_glDeleteBuffers},
{"org/mini/gl/GL",  "glDeleteFramebuffers",  "(I[II)V",  org_mini_gl_GL_glDeleteFramebuffers},
{"org/mini/gl/GL",  "glDeleteProgram",  "(I)V",  org_mini_gl_GL_glDeleteProgram},
{"org/mini/gl/GL",  "glDeleteRenderbuffers",  "(I[II)V",  org_mini_gl_GL_glDeleteRenderbuffers},
{"org/mini/gl/GL",  "glDeleteShader",  "(I)V",  org_mini_gl_GL_glDeleteShader},
{"org/mini/gl/GL",  "glDeleteTextures",  "(I[II)V",  org_mini_gl_GL_glDeleteTextures},
{"org/mini/gl/GL",  "glDepthFunc",  "(I)V",  org_mini_gl_GL_glDepthFunc},
{"org/mini/gl/GL",  "glDepthMask",  "(I)V",  org_mini_gl_GL_glDepthMask},
{"org/mini/gl/GL",  "glDepthRangef",  "(FF)V",  org_mini_gl_GL_glDepthRangef},
{"org/mini/gl/GL",  "glDetachShader",  "(II)V",  org_mini_gl_GL_glDetachShader},
{"org/mini/gl/GL",  "glDisable",  "(I)V",  org_mini_gl_GL_glDisable},
{"org/mini/gl/GL",  "glDisableVertexAttribArray",  "(I)V",  org_mini_gl_GL_glDisableVertexAttribArray},
{"org/mini/gl/GL",  "glDrawArrays",  "(III)V",  org_mini_gl_GL_glDrawArrays},
{"org/mini/gl/GL",  "glDrawElements",  "(IIILjava/lang/Object;I)V",  org_mini_gl_GL_glDrawElements},
{"org/mini/gl/GL",  "glEnable",  "(I)V",  org_mini_gl_GL_glEnable},
{"org/mini/gl/GL",  "glEnableVertexAttribArray",  "(I)V",  org_mini_gl_GL_glEnableVertexAttribArray},
{"org/mini/gl/GL",  "glFinish",  "()V",  org_mini_gl_GL_glFinish},
{"org/mini/gl/GL",  "glFlush",  "()V",  org_mini_gl_GL_glFlush},
{"org/mini/gl/GL",  "glFramebufferRenderbuffer",  "(IIII)V",  org_mini_gl_GL_glFramebufferRenderbuffer},
{"org/mini/gl/GL",  "glFramebufferTexture2D",  "(IIIII)V",  org_mini_gl_GL_glFramebufferTexture2D},
{"org/mini/gl/GL",  "glFrontFace",  "(I)V",  org_mini_gl_GL_glFrontFace},
{"org/mini/gl/GL",  "glGenBuffers",  "(I[II)V",  org_mini_gl_GL_glGenBuffers},
{"org/mini/gl/GL",  "glGenerateMipmap",  "(I)V",  org_mini_gl_GL_glGenerateMipmap},
{"org/mini/gl/GL",  "glGenFramebuffers",  "(I[II)V",  org_mini_gl_GL_glGenFramebuffers},
{"org/mini/gl/GL",  "glGenRenderbuffers",  "(I[II)V",  org_mini_gl_GL_glGenRenderbuffers},
{"org/mini/gl/GL",  "glGenTextures",  "(I[II)V",  org_mini_gl_GL_glGenTextures},
{"org/mini/gl/GL",  "glGetActiveAttrib",  "(III[II[II[II[B)V",  org_mini_gl_GL_glGetActiveAttrib},
{"org/mini/gl/GL",  "glGetActiveUniform",  "(III[II[II[II[B)V",  org_mini_gl_GL_glGetActiveUniform},
{"org/mini/gl/GL",  "glGetAttachedShaders",  "(II[II[II)V",  org_mini_gl_GL_glGetAttachedShaders},
{"org/mini/gl/GL",  "glGetAttribLocation",  "(I[B)I",  org_mini_gl_GL_glGetAttribLocation},
{"org/mini/gl/GL",  "glGetBooleanv",  "(I[II)V",  org_mini_gl_GL_glGetBooleanv},
{"org/mini/gl/GL",  "glGetBufferParameteriv",  "(II[II)V",  org_mini_gl_GL_glGetBufferParameteriv},
{"org/mini/gl/GL",  "glGetError",  "()I",  org_mini_gl_GL_glGetError},
{"org/mini/gl/GL",  "glGetFloatv",  "(I[FI)V",  org_mini_gl_GL_glGetFloatv},
{"org/mini/gl/GL",  "glGetFramebufferAttachmentParameteriv",  "(III[II)V",  org_mini_gl_GL_glGetFramebufferAttachmentParameteriv},
{"org/mini/gl/GL",  "glGetIntegerv",  "(I[II)V",  org_mini_gl_GL_glGetIntegerv},
{"org/mini/gl/GL",  "glGetProgramiv",  "(II[II)V",  org_mini_gl_GL_glGetProgramiv},
{"org/mini/gl/GL",  "glGetProgramInfoLog",  "(II[II[B)V",  org_mini_gl_GL_glGetProgramInfoLog},
{"org/mini/gl/GL",  "glGetRenderbufferParameteriv",  "(II[II)V",  org_mini_gl_GL_glGetRenderbufferParameteriv},
{"org/mini/gl/GL",  "glGetShaderiv",  "(II[II)V",  org_mini_gl_GL_glGetShaderiv},
{"org/mini/gl/GL",  "glGetShaderInfoLog",  "(II[II[B)V",  org_mini_gl_GL_glGetShaderInfoLog},
{"org/mini/gl/GL",  "glGetShaderPrecisionFormat",  "(II[II[II)V",  org_mini_gl_GL_glGetShaderPrecisionFormat},
{"org/mini/gl/GL",  "glGetShaderSource",  "(II[II[B)V",  org_mini_gl_GL_glGetShaderSource},
{"org/mini/gl/GL",  "glGetString",  "(I)[B",  org_mini_gl_GL_glGetString},
{"org/mini/gl/GL",  "glGetTexParameterfv",  "(II[FI)V",  org_mini_gl_GL_glGetTexParameterfv},
{"org/mini/gl/GL",  "glGetTexParameteriv",  "(II[II)V",  org_mini_gl_GL_glGetTexParameteriv},
{"org/mini/gl/GL",  "glGetUniformfv",  "(II[FI)V",  org_mini_gl_GL_glGetUniformfv},
{"org/mini/gl/GL",  "glGetUniformiv",  "(II[II)V",  org_mini_gl_GL_glGetUniformiv},
{"org/mini/gl/GL",  "glGetUniformLocation",  "(I[B)I",  org_mini_gl_GL_glGetUniformLocation},
{"org/mini/gl/GL",  "glGetVertexAttribfv",  "(II[FI)V",  org_mini_gl_GL_glGetVertexAttribfv},
{"org/mini/gl/GL",  "glGetVertexAttribiv",  "(II[II)V",  org_mini_gl_GL_glGetVertexAttribiv},
{"org/mini/gl/GL",  "glGetVertexAttribPointerv",  "(II[Ljava/lang/Object;)V",  org_mini_gl_GL_glGetVertexAttribPointerv},
{"org/mini/gl/GL",  "glHint",  "(II)V",  org_mini_gl_GL_glHint},
{"org/mini/gl/GL",  "glIsBuffer",  "(I)I",  org_mini_gl_GL_glIsBuffer},
{"org/mini/gl/GL",  "glIsEnabled",  "(I)I",  org_mini_gl_GL_glIsEnabled},
{"org/mini/gl/GL",  "glIsFramebuffer",  "(I)I",  org_mini_gl_GL_glIsFramebuffer},
{"org/mini/gl/GL",  "glIsProgram",  "(I)I",  org_mini_gl_GL_glIsProgram},
{"org/mini/gl/GL",  "glIsRenderbuffer",  "(I)I",  org_mini_gl_GL_glIsRenderbuffer},
{"org/mini/gl/GL",  "glIsShader",  "(I)I",  org_mini_gl_GL_glIsShader},
{"org/mini/gl/GL",  "glIsTexture",  "(I)I",  org_mini_gl_GL_glIsTexture},
{"org/mini/gl/GL",  "glLineWidth",  "(F)V",  org_mini_gl_GL_glLineWidth},
{"org/mini/gl/GL",  "glLinkProgram",  "(I)V",  org_mini_gl_GL_glLinkProgram},
{"org/mini/gl/GL",  "glPixelStorei",  "(II)V",  org_mini_gl_GL_glPixelStorei},
{"org/mini/gl/GL",  "glPolygonOffset",  "(FF)V",  org_mini_gl_GL_glPolygonOffset},
{"org/mini/gl/GL",  "glReadPixels",  "(IIIIIILjava/lang/Object;I)V",  org_mini_gl_GL_glReadPixels},
{"org/mini/gl/GL",  "glReleaseShaderCompiler",  "()V",  org_mini_gl_GL_glReleaseShaderCompiler},
{"org/mini/gl/GL",  "glRenderbufferStorage",  "(IIII)V",  org_mini_gl_GL_glRenderbufferStorage},
{"org/mini/gl/GL",  "glSampleCoverage",  "(FI)V",  org_mini_gl_GL_glSampleCoverage},
{"org/mini/gl/GL",  "glScissor",  "(IIII)V",  org_mini_gl_GL_glScissor},
{"org/mini/gl/GL",  "glShaderBinary",  "(I[IIILjava/lang/Object;II)V",  org_mini_gl_GL_glShaderBinary},
{"org/mini/gl/GL",  "glShaderSource",  "(II[[B[II)V",  org_mini_gl_GL_glShaderSource},
{"org/mini/gl/GL",  "glStencilFunc",  "(III)V",  org_mini_gl_GL_glStencilFunc},
{"org/mini/gl/GL",  "glStencilFuncSeparate",  "(IIII)V",  org_mini_gl_GL_glStencilFuncSeparate},
{"org/mini/gl/GL",  "glStencilMask",  "(I)V",  org_mini_gl_GL_glStencilMask},
{"org/mini/gl/GL",  "glStencilMaskSeparate",  "(II)V",  org_mini_gl_GL_glStencilMaskSeparate},
{"org/mini/gl/GL",  "glStencilOp",  "(III)V",  org_mini_gl_GL_glStencilOp},
{"org/mini/gl/GL",  "glStencilOpSeparate",  "(IIII)V",  org_mini_gl_GL_glStencilOpSeparate},
{"org/mini/gl/GL",  "glTexImage2D",  "(IIIIIIIILjava/lang/Object;I)V",  org_mini_gl_GL_glTexImage2D},
{"org/mini/gl/GL",  "glTexParameterf",  "(IIF)V",  org_mini_gl_GL_glTexParameterf},
{"org/mini/gl/GL",  "glTexParameterfv",  "(II[FI)V",  org_mini_gl_GL_glTexParameterfv},
{"org/mini/gl/GL",  "glTexParameteri",  "(III)V",  org_mini_gl_GL_glTexParameteri},
{"org/mini/gl/GL",  "glTexParameteriv",  "(II[II)V",  org_mini_gl_GL_glTexParameteriv},
{"org/mini/gl/GL",  "glTexSubImage2D",  "(IIIIIIIILjava/lang/Object;I)V",  org_mini_gl_GL_glTexSubImage2D},
{"org/mini/gl/GL",  "glUniform1f",  "(IF)V",  org_mini_gl_GL_glUniform1f},
{"org/mini/gl/GL",  "glUniform1fv",  "(II[FI)V",  org_mini_gl_GL_glUniform1fv},
{"org/mini/gl/GL",  "glUniform1i",  "(II)V",  org_mini_gl_GL_glUniform1i},
{"org/mini/gl/GL",  "glUniform1iv",  "(II[II)V",  org_mini_gl_GL_glUniform1iv},
{"org/mini/gl/GL",  "glUniform2f",  "(IFF)V",  org_mini_gl_GL_glUniform2f},
{"org/mini/gl/GL",  "glUniform2fv",  "(II[FI)V",  org_mini_gl_GL_glUniform2fv},
{"org/mini/gl/GL",  "glUniform2i",  "(III)V",  org_mini_gl_GL_glUniform2i},
{"org/mini/gl/GL",  "glUniform2iv",  "(II[II)V",  org_mini_gl_GL_glUniform2iv},
{"org/mini/gl/GL",  "glUniform3f",  "(IFFF)V",  org_mini_gl_GL_glUniform3f},
{"org/mini/gl/GL",  "glUniform3fv",  "(II[FI)V",  org_mini_gl_GL_glUniform3fv},
{"org/mini/gl/GL",  "glUniform3i",  "(IIII)V",  org_mini_gl_GL_glUniform3i},
{"org/mini/gl/GL",  "glUniform3iv",  "(II[II)V",  org_mini_gl_GL_glUniform3iv},
{"org/mini/gl/GL",  "glUniform4f",  "(IFFFF)V",  org_mini_gl_GL_glUniform4f},
{"org/mini/gl/GL",  "glUniform4fv",  "(II[FI)V",  org_mini_gl_GL_glUniform4fv},
{"org/mini/gl/GL",  "glUniform4i",  "(IIIII)V",  org_mini_gl_GL_glUniform4i},
{"org/mini/gl/GL",  "glUniform4iv",  "(II[II)V",  org_mini_gl_GL_glUniform4iv},
{"org/mini/gl/GL",  "glUniformMatrix2fv",  "(III[FI)V",  org_mini_gl_GL_glUniformMatrix2fv},
{"org/mini/gl/GL",  "glUniformMatrix3fv",  "(III[FI)V",  org_mini_gl_GL_glUniformMatrix3fv},
{"org/mini/gl/GL",  "glUniformMatrix4fv",  "(III[FI)V",  org_mini_gl_GL_glUniformMatrix4fv},
{"org/mini/gl/GL",  "glUseProgram",  "(I)V",  org_mini_gl_GL_glUseProgram},
{"org/mini/gl/GL",  "glValidateProgram",  "(I)V",  org_mini_gl_GL_glValidateProgram},
{"org/mini/gl/GL",  "glVertexAttrib1f",  "(IF)V",  org_mini_gl_GL_glVertexAttrib1f},
{"org/mini/gl/GL",  "glVertexAttrib1fv",  "(I[FI)V",  org_mini_gl_GL_glVertexAttrib1fv},
{"org/mini/gl/GL",  "glVertexAttrib2f",  "(IFF)V",  org_mini_gl_GL_glVertexAttrib2f},
{"org/mini/gl/GL",  "glVertexAttrib2fv",  "(I[FI)V",  org_mini_gl_GL_glVertexAttrib2fv},
{"org/mini/gl/GL",  "glVertexAttrib3f",  "(IFFF)V",  org_mini_gl_GL_glVertexAttrib3f},
{"org/mini/gl/GL",  "glVertexAttrib3fv",  "(I[FI)V",  org_mini_gl_GL_glVertexAttrib3fv},
{"org/mini/gl/GL",  "glVertexAttrib4f",  "(IFFFF)V",  org_mini_gl_GL_glVertexAttrib4f},
{"org/mini/gl/GL",  "glVertexAttrib4fv",  "(I[FI)V",  org_mini_gl_GL_glVertexAttrib4fv},
{"org/mini/gl/GL",  "glVertexAttribPointer",  "(IIIIILjava/lang/Object;I)V",  org_mini_gl_GL_glVertexAttribPointer},
{"org/mini/gl/GL",  "glViewport",  "(IIII)V",  org_mini_gl_GL_glViewport},
};

s32 count_GLFuncTable() {
    return sizeof(method_gl_table) / sizeof(java_native_method);
}

__refer ptr_GLFuncTable() {
    return &method_gl_table[0];
}
