/*this file generated by Nutil_java_2_c.java ,dont modify it manual.*/
#include <stdio.h>
#include <string.h>

#include <glad/glad.h>
#include <GLFW/glfw3.h>

#define STB_TRUETYPE_IMPLEMENTATION
#include <stb_truetype.h>
#define STB_IMAGE_WRITE_IMPLEMENTATION
#include <stb_image_write.h>


#include "../mini_jvm/jvm/jvm.h"
#include "jni_gui.h"
#include "stb_jni_assist.h"



int org_mini_glfw_utils_Nutil_stbtt_InitFont(Runtime *runtime, Class *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    intptr_t pinfo = env->localvar_getLong_2slot(runtime, pos);pos += 2;
    Instance *pdata2 = env->localvar_getRefer(runtime, pos++);
    __refer ptr_pdata2 = NULL;
    if(pdata2){
        ptr_pdata2 = pdata2->arr_body;
    }
    s32 pfontstart = env->localvar_getInt(runtime, pos++);

    int _re_val = stbtt_InitFont((stbtt_fontinfo*/*ptr*/)(pinfo), (const unsigned char*)(ptr_pdata2), (int)pfontstart);
    s32 ret_value = (s32)_re_val;env->push_int(runtime->stack, ret_value);
    
    return 0;
}

int org_mini_glfw_utils_Nutil_stbtt_ScaleForPixelHeight(Runtime *runtime, Class *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    intptr_t pinfo = env->localvar_getLong_2slot(runtime, pos);pos += 2;
    Int2Float ppixels;ppixels.i = env->localvar_getInt(runtime, pos++);

    f32 ret_value = (f32)stbtt_ScaleForPixelHeight((const stbtt_fontinfo*/*ptr*/)(pinfo), (float)ppixels.f);
    env->push_float(runtime->stack, ret_value);
    
    return 0;
}

int org_mini_glfw_utils_Nutil_stbtt_GetFontVMetrics(Runtime *runtime, Class *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    intptr_t pinfo = env->localvar_getLong_2slot(runtime, pos);pos += 2;
    Instance *pascent = env->localvar_getRefer(runtime, pos++);
    __refer ptr_pascent = NULL;
    if(pascent){
        ptr_pascent = pascent->arr_body;
    }
    Instance *pdescent = env->localvar_getRefer(runtime, pos++);
    __refer ptr_pdescent = NULL;
    if(pdescent){
        ptr_pdescent = pdescent->arr_body;
    }
    Instance *plineGap = env->localvar_getRefer(runtime, pos++);
    __refer ptr_plineGap = NULL;
    if(plineGap){
        ptr_plineGap = plineGap->arr_body;
    }

    stbtt_GetFontVMetrics((const stbtt_fontinfo*/*ptr*/)(pinfo), (int*)(ptr_pascent), (int*)(ptr_pdescent), (int*)(ptr_plineGap));
    
    
    return 0;
}

int org_mini_glfw_utils_Nutil_stbtt_GetCodepointBitmapBox(Runtime *runtime, Class *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    intptr_t pfont = env->localvar_getLong_2slot(runtime, pos);pos += 2;
    s32 pcodepoint = env->localvar_getInt(runtime, pos++);
    Int2Float pscale_x;pscale_x.i = env->localvar_getInt(runtime, pos++);
    Int2Float pscale_y;pscale_y.i = env->localvar_getInt(runtime, pos++);
    Instance *pix0 = env->localvar_getRefer(runtime, pos++);
    __refer ptr_pix0 = NULL;
    if(pix0){
        ptr_pix0 = pix0->arr_body;
    }
    Instance *piy0 = env->localvar_getRefer(runtime, pos++);
    __refer ptr_piy0 = NULL;
    if(piy0){
        ptr_piy0 = piy0->arr_body;
    }
    Instance *pix1 = env->localvar_getRefer(runtime, pos++);
    __refer ptr_pix1 = NULL;
    if(pix1){
        ptr_pix1 = pix1->arr_body;
    }
    Instance *piy1 = env->localvar_getRefer(runtime, pos++);
    __refer ptr_piy1 = NULL;
    if(piy1){
        ptr_piy1 = piy1->arr_body;
    }

    stbtt_GetCodepointBitmapBox((const stbtt_fontinfo*/*ptr*/)(pfont), (int)pcodepoint, (float)pscale_x.f, (float)pscale_y.f, (int*)(ptr_pix0), (int*)(ptr_piy0), (int*)(ptr_pix1), (int*)(ptr_piy1));
    
    
    return 0;
}

int org_mini_glfw_utils_Nutil_stbtt_MakeCodepointBitmapOffset(Runtime *runtime, Class *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    intptr_t pinfo = env->localvar_getLong_2slot(runtime, pos);pos += 2;
    Instance *poutput = env->localvar_getRefer(runtime, pos++);
    __refer ptr_poutput = NULL;
    if(poutput){
        ptr_poutput = poutput->arr_body;
    }
    s32 poutput_offset = env->localvar_getInt(runtime, pos++);
    s32 pout_w = env->localvar_getInt(runtime, pos++);
    s32 pout_h = env->localvar_getInt(runtime, pos++);
    s32 pout_stride = env->localvar_getInt(runtime, pos++);
    Int2Float pscale_x;pscale_x.i = env->localvar_getInt(runtime, pos++);
    Int2Float pscale_y;pscale_y.i = env->localvar_getInt(runtime, pos++);
    s32 pcodepoint = env->localvar_getInt(runtime, pos++);

    stbtt_MakeCodepointBitmapOffset((const stbtt_fontinfo*/*ptr*/)(pinfo), (unsigned char*)(ptr_poutput), (int)poutput_offset, (int)pout_w, (int)pout_h, (int)pout_stride, (float)pscale_x.f, (float)pscale_y.f, (int)pcodepoint);
    
    
    return 0;
}

int org_mini_glfw_utils_Nutil_stbtt_GetCodepointHMetrics(Runtime *runtime, Class *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    intptr_t pinfo = env->localvar_getLong_2slot(runtime, pos);pos += 2;
    s32 pcodepoint = env->localvar_getInt(runtime, pos++);
    Instance *padvanceWidth = env->localvar_getRefer(runtime, pos++);
    __refer ptr_padvanceWidth = NULL;
    if(padvanceWidth){
        ptr_padvanceWidth = padvanceWidth->arr_body;
    }
    Instance *pleftSideBearing = env->localvar_getRefer(runtime, pos++);
    __refer ptr_pleftSideBearing = NULL;
    if(pleftSideBearing){
        ptr_pleftSideBearing = pleftSideBearing->arr_body;
    }

    stbtt_GetCodepointHMetrics((const stbtt_fontinfo*/*ptr*/)(pinfo), (int)pcodepoint, (int*)(ptr_padvanceWidth), (int*)(ptr_pleftSideBearing));
    
    
    return 0;
}

int org_mini_glfw_utils_Nutil_stbtt_GetCodepointKernAdvance(Runtime *runtime, Class *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    intptr_t pinfo = env->localvar_getLong_2slot(runtime, pos);pos += 2;
    s32 pch1 = env->localvar_getInt(runtime, pos++);
    s32 pch2 = env->localvar_getInt(runtime, pos++);

    int _re_val = stbtt_GetCodepointKernAdvance((const stbtt_fontinfo*/*ptr*/)(pinfo), (int)pch1, (int)pch2);
    s32 ret_value = (s32)_re_val;env->push_int(runtime->stack, ret_value);
    
    return 0;
}

int org_mini_glfw_utils_Nutil_stbtt_MakeFontInfo(Runtime *runtime, Class *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    

    struct stbtt_fontinfo/*none_ptr*/ _re_val = stbtt_MakeFontInfo();
    c8* _ptr_re_val = (c8*)&_re_val;
    s32 _struct_bytes = sizeof(_re_val);
    if (_ptr_re_val) {
        s32 _j_t_bytes = sizeof(c8);
        Instance *_arr = env->jarray_create(_struct_bytes / _j_t_bytes, DATATYPE_BYTE, NULL);
        memcpy(_arr->arr_body, _ptr_re_val,_struct_bytes);
        env->push_ref(runtime->stack, _arr);
    } else {
        env->push_ref(runtime->stack, NULL);
    }
    
    return 0;
}

int org_mini_glfw_utils_Nutil_stbi_write_png(Runtime *runtime, Class *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    Instance *pfilename = env->localvar_getRefer(runtime, pos++);
    __refer ptr_pfilename = NULL;
    if(pfilename){
        ptr_pfilename = pfilename->arr_body;
    }
    s32 pw = env->localvar_getInt(runtime, pos++);
    s32 ph = env->localvar_getInt(runtime, pos++);
    s32 pcomp = env->localvar_getInt(runtime, pos++);
    intptr_t pdata = env->localvar_getLong_2slot(runtime, pos);pos += 2;
    s32 pstride_in_bytes = env->localvar_getInt(runtime, pos++);

    int _re_val = stbi_write_png((char const*)(ptr_pfilename), (int)pw, (int)ph, (int)pcomp, (const void*/*ptr*/)(pdata), (int)pstride_in_bytes);
    s32 ret_value = (s32)_re_val;env->push_int(runtime->stack, ret_value);
    
    return 0;
}

int org_mini_glfw_utils_Nutil_stbi_write_bmp(Runtime *runtime, Class *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    Instance *pfilename = env->localvar_getRefer(runtime, pos++);
    __refer ptr_pfilename = NULL;
    if(pfilename){
        ptr_pfilename = pfilename->arr_body;
    }
    s32 pw = env->localvar_getInt(runtime, pos++);
    s32 ph = env->localvar_getInt(runtime, pos++);
    s32 pcomp = env->localvar_getInt(runtime, pos++);
    intptr_t pdata = env->localvar_getLong_2slot(runtime, pos);pos += 2;

    int _re_val = stbi_write_bmp((char const*)(ptr_pfilename), (int)pw, (int)ph, (int)pcomp, (const void*/*ptr*/)(pdata));
    s32 ret_value = (s32)_re_val;env->push_int(runtime->stack, ret_value);
    
    return 0;
}

int org_mini_glfw_utils_Nutil_stbi_write_tga(Runtime *runtime, Class *clazz) {
    JniEnv *env = runtime->jnienv;
    s32 pos = 0;
    
    Instance *pfilename = env->localvar_getRefer(runtime, pos++);
    __refer ptr_pfilename = NULL;
    if(pfilename){
        ptr_pfilename = pfilename->arr_body;
    }
    s32 pw = env->localvar_getInt(runtime, pos++);
    s32 ph = env->localvar_getInt(runtime, pos++);
    s32 pcomp = env->localvar_getInt(runtime, pos++);
    intptr_t pdata = env->localvar_getLong_2slot(runtime, pos);pos += 2;

    int _re_val = stbi_write_tga((char const*)(ptr_pfilename), (int)pw, (int)ph, (int)pcomp, (const void*/*ptr*/)(pdata));
    s32 ret_value = (s32)_re_val;env->push_int(runtime->stack, ret_value);
    
    return 0;
}




static java_native_method method_nutil_table[] = {

{"org/mini/glfw/utils/Nutil",  "stbtt_InitFont",  "(J[BI)I",  org_mini_glfw_utils_Nutil_stbtt_InitFont},
{"org/mini/glfw/utils/Nutil",  "stbtt_ScaleForPixelHeight",  "(JF)F",  org_mini_glfw_utils_Nutil_stbtt_ScaleForPixelHeight},
{"org/mini/glfw/utils/Nutil",  "stbtt_GetFontVMetrics",  "(J[I[I[I)V",  org_mini_glfw_utils_Nutil_stbtt_GetFontVMetrics},
{"org/mini/glfw/utils/Nutil",  "stbtt_GetCodepointBitmapBox",  "(JIFF[I[I[I[I)V",  org_mini_glfw_utils_Nutil_stbtt_GetCodepointBitmapBox},
{"org/mini/glfw/utils/Nutil",  "stbtt_MakeCodepointBitmapOffset",  "(J[BIIIIFFI)V",  org_mini_glfw_utils_Nutil_stbtt_MakeCodepointBitmapOffset},
{"org/mini/glfw/utils/Nutil",  "stbtt_GetCodepointHMetrics",  "(JI[I[I)V",  org_mini_glfw_utils_Nutil_stbtt_GetCodepointHMetrics},
{"org/mini/glfw/utils/Nutil",  "stbtt_GetCodepointKernAdvance",  "(JII)I",  org_mini_glfw_utils_Nutil_stbtt_GetCodepointKernAdvance},
{"org/mini/glfw/utils/Nutil",  "stbtt_MakeFontInfo",  "()[B",  org_mini_glfw_utils_Nutil_stbtt_MakeFontInfo},
{"org/mini/glfw/utils/Nutil",  "stbi_write_png",  "([BIIIJI)I",  org_mini_glfw_utils_Nutil_stbi_write_png},
{"org/mini/glfw/utils/Nutil",  "stbi_write_bmp",  "([BIIIJ)I",  org_mini_glfw_utils_Nutil_stbi_write_bmp},
{"org/mini/glfw/utils/Nutil",  "stbi_write_tga",  "([BIIIJ)I",  org_mini_glfw_utils_Nutil_stbi_write_tga},
};

s32 count_NutilFuncTable() {
    return sizeof(method_nutil_table) / sizeof(java_native_method);
}

__refer ptr_NutilFuncTable() {
    return &method_nutil_table[0];
}